/* ============================================================
   COPY — Strings de i18n (PT-BR / EN) do app
   ============================================================
   Originalmente em app.jsx [00]. Extraído na Fase 0 da refatoração.
   Acessível como `COPY` (global) ou `window.COPY` (para o painel
   de tweaks ou outros consumidores externos).
   ============================================================ */
/* ============================== [00] COPY / i18n ============================== */

// PT-BR and EN copy
const COPY = {
  pt: {
    convites: {
      mng: {
        titulo: 'Gerenciar convites',
        fechar: 'Fechar',
        gerando: 'Gerando…',
        novoConvite: 'Gerar convite',
        descricao: 'Agora que sua aventura foi criada, é hora de convidar os jogadores. Compartilhe com eles o código gerado abaixo. Para participar, cada jogador deve primeiro criar um novo personagem. Depois disso, basta usar o código da aventura para entrar na sua mesa e começar a jornada.',
        carregando: 'Carregando…',
        vazio: 'Você ainda não gerou nenhum convite.',
        uiKitAusente: 'Kit de UI não carregado (ui-bridge).',
        copiar: 'Copiar',
        copiado: 'Copiado',
        reativar: 'Reativar',
        remover: 'Remover',
        falhouComMotivo: 'Falhou: {motivo}',
        falhouDesconhecido: 'desconhecido',
      },
      status: {
        ativo: 'Ativo',
        usado: 'Usado',
        revogado: 'Revogado',
        expirado: 'Expirado',
      },
      jogador: {
        digiteCodigoPrimeiro: 'Digite um código primeiro',
        semPersonagem: 'Você ainda não criou um personagem — é necessário criar um antes de aceitar o convite',
        instrucao: 'Para participar de uma aventura, cole o código que o mestre compartilhou com você no campo abaixo.',
        continuar: 'Continuar',
        escolherPj: 'Escolha qual personagem você quer vincular a esta história ({codigo}):',
        voltar: 'Voltar',
        aceitando: 'Aceitando…',
        aceitarConvite: 'Aceitar convite',
        conviteAceito: 'Convite aceito!',
        sucesso: 'Seu personagem {pjNome} agora faz parte de {historiaTitulo}.',
        aceitarOutro: 'Aceitar outro',
        dataADefinir: 'Data a definir',
      },
      motivo: {
        codigo_invalido: 'Código inválido',
        convite_expirado: 'Convite expirado',
        convite_ja_usado: 'Convite já foi usado',
        convite_revogado: 'Convite foi revogado pelo Mestre',
        pj_nao_pertence: 'Esse personagem não é seu',
        pj_nao_encontrado: 'Personagem não encontrado',
        pj_ja_vinculado: 'Esse personagem já está nessa mesa',
        nao_autenticado: 'Sessão expirada — faça login de novo',
      },
      aceitarModal: {
        concluir: 'Concluir',
        entrarMesa: 'Entrar em uma mesa',
        depois: 'Depois',
        convitePrompt: 'Recebeu um código de convite de um Mestre? Use-o para levar {nomePj} para uma história.',
      },
    },
    historias: {
      lista: {
        carregando: 'Abrindo os pergaminhos…',
        erroTabela: "Confira se a tabela 'historias' existe no Supabase.",
        comecarAventura: 'Comece uma nova aventura quando estiver pronto',
        limitePlanoFree: 'Você atingiu o limite de histórias do plano gratuito — faça um upgrade',
        novaHistoria: 'Nova história',
      },
      card: {
        batalhas: 'Batalhas',
        convites: 'Convites',
        lore: 'Lore',
        loreTip: 'Lore (NPCs, Reinos, Cidades)',
        lojaTip: 'Loja ({qtd})',
        loja: 'Loja',
        editar: 'Editar',
        excluir: 'Excluir',
        protagonistas: 'Protagonistas',
      },
      excluirModal: {
        titulo: 'Excluir?',
        confirmar: 'Excluir',
        aviso: 'A história "{titulo}" será removida permanentemente.',
      },
      loja: {
        shop: 'Loja',
        shopSub: 'Itens à venda para os jogadores de {titulo}.',
        catalog: 'Catálogo',
        catalogSub: 'Busque por nome, descrição ou origem.',
        empty: 'Escolha um item no catálogo',
        none: 'Nenhum item corresponde.',
        loading: 'Abrindo o catálogo…',
        price: 'Preço',
        stock: 'Estoque',
        remove: 'Remover',
        cancel: 'Cancelar',
        save: 'Salvar',
        saving: 'Salvando…',
        search: 'Buscar…',
        allGroups: 'Todos os grupos',
        clear: 'Limpar',
        inDesc: 'na descrição',
        inOrig: 'na origem',
        inDetails: 'nos detalhes',
        catalogPrice: 'Preço do catálogo',
        addToShop: 'Adicionar',
        origin: 'Origem',
        liquid: 'líquido',
        magic: 'mágico',
        moedaOuro: 'O',
        moedaPrata: 'P',
        moedaCobre: 'C',
        moedaLatao: 'L',
        gratis: 'grátis',
        inShopSingular: '{n} item na loja',
        inShopPlural: '{n} itens na loja',
        showing: '{n} de {total}',
        paginaPrimeira: 'Primeira página',
        paginaAnterior: 'Anterior',
        paginaProxima: 'Próxima',
        paginaUltima: 'Última página',
        paginaInfo: 'Página {atual} de {total}',
      },
      novaModal: {
        editarTitulo: 'Editar história',
        novaTitulo: 'Nova história',
        salvando: 'Salvando…',
        salvar: 'Salvar',
        criar: 'Criar',
        titulo: 'Título',
        tituloPlaceholder: 'A Sombra de Verrogar',
        reino: 'Reino',
        reinoPlaceholder: 'Verrogar',
        dataInicio: 'Data de início',
        dataInicioJogo: 'Data de início no jogo',
        criaturas: 'Criaturas',
        selecionadas: 'selecionadas',
        semCriaturas: 'Nenhuma criatura disponível no bestiário',
      },
    },
    lore: {
      form: {
        nome: 'Nome',
        descricao: 'Descrição',
        imagem: 'Imagem (URL, opcional)',
        deus: 'Deus',
        raca: 'Raça',
        localizacao: 'Localização',
        cidadeNatal: 'Cidade Natal',
        classeSocial: 'Classe Social',
        idade: 'Idade',
        familia: 'Família',
        relacao: 'Relação',
        status: 'Status',
        rumores: 'Rumores',
        icone: 'Ícone (URL, opcional)',
        governo: 'Governo',
        cultura: 'Cultura',
        historiaRecente: 'História recente',
        reino: 'Reino',
        populacao: 'População',
        capitalDoReino: 'É a capital do reino',
      },
    },
    inventario: {
      abaterEPreparar: 'Abater e preparar {nome}? Você receberá {qtd}× {consumivel}.',
      abrindoAsAlgibeiras: 'Abrindo as algibeiras…',
      aprendendo: 'Aprendendo…',
      aprender: 'Aprender',
      armaduras: 'Armaduras',
      armazenar: 'Armazenar',
      buscar: 'Buscar…',
      cancelar: 'Cancelar',
      capacidade: 'Capacidade',
      cargaPesada: 'Carga pesada',
      carregando: 'Carregando',
      confiraSeATabela: 'Confira se a tabela \'itens\' e a coluna \'inventario\' existem no Supabase.',
      confirmar: 'Confirmar',
      cuidadoEssaAcaoE: 'Cuidado, essa ação é irreversível.',
      deMax: 'de {max}',
      descartar: 'Descartar',
      desequipar: 'Desequipar',
      despir: 'Despir',
      destruirEsteItemPermanentemente: 'Destruir este item permanentemente?',
      destruirItem: 'Destruir item',
      detalhes: 'Detalhes',
      efeito: 'Efeito',
      enviando: 'Enviando…',
      equipar: 'Equipar',
      esteItemNaoE: 'Este item não é um pergaminho de magia.',
      falhaAoSalvar: 'Falha ao salvar',
      gratis: 'Grátis',
      liquidos: 'líquidos',
      magiaNaoEncontradaNo: 'Magia não encontrada no catálogo.',
      max: 'Máx',
      mesaUsouItem: '{nome} usou {item}.',
      moedas: 'Moedas',
      naoFoiPossivelAprender: 'Não foi possível aprender a magia.',
      nenhumRecipienteCompativelNo: 'Nenhum recipiente compatível no inventário',
      nivelDeMagiaInvalido: 'Nível de magia inválido no pergaminho.',
      oNivelDaMagia: 'O nível da magia passa do seu estágio.',
      ocupadoPorEquip: '{slot} ocupado por equipamento.',
      outros: 'Outros',
      pergaminhoNaoEncontradoNo: 'Pergaminho não encontrado no inventário.',
      personagemNaoEncontrado: 'Personagem não encontrado.',
      peso: 'Peso',
      pontosDeMagiaInsuficientes: 'Pontos de magia insuficientes.',
      precisaMaosLivres: 'Precisa de {maos} mão(s) livre(s) ({livres} livre{s}).',
      preparar: 'Preparar',
      prepararAnimal: 'Preparar animal',
      proibidoParaRaca: 'Proibido para {raca}.',
      pt: 'pt',
      ptBr: 'pt-BR',
      salvando: 'Salvando…',
      salvo: 'Salvo',
      semSlotDefinido: 'Sem slot definido.',
      semSlotDefinidoPara: 'Sem slot definido para este item.',
      simDestruir: 'Sim, destruir',
      simPreparar: 'Sim, preparar',
      simUsar: 'Sim, usar',
      slotCheio: 'Slot cheio ({usado}/{max}).',
      slotOcupado: 'Slot {slot} ocupado.',
      sobrecarregado: 'Sobrecarregado!',
      solidos: 'sólidos',
      suaProfissaoNaoPode: 'Sua profissão não pode aprender essa magia.',
      tituloArmazenar: 'Armazenar {nome}',
      tituloDestruir: 'Destruir {nome}',
      tituloRetirar: 'Retirar {nome}',
      tituloUsar: 'Usar {nome}',
      todos: 'Todos',
      transferir: 'Transferir',
      usar: 'Usar',
      usarEsteItem: 'Usar este item?',
      usarItem: 'Usar item',
      vestimentas: 'Vestimentas',
      vestir: 'Vestir',
      voceJaTemEssa: 'Você já tem essa magia neste nível ou superior.',
      voceNaoEstaAutenticado: 'Você não está autenticado.',
      voceNaoTemNenhum: 'Você não tem nenhum pertence.',
      vocePrecisaAprenderO: 'Você precisa aprender o nível anterior primeiro.',
      zerar: 'Zerar',
    },
    loja: {
      abraFicha: 'Abra a ficha de um personagem para acessar a loja dele',
      abrindoALoja: 'Abrindo a loja…',
      absorcao: 'Absorção',
      alcance: 'Alcance',
      armazena: 'Armazena',
      buscar: 'Buscar…',
      cancelar: 'Cancelar',
      comprar: 'Comprar',
      comprou: 'Você comprou {qtd} {nome}.',
      dano: 'Dano',
      de: 'de',
      e: ' e ',
      efeito: 'Efeito',
      escolhaUmRecipiente: 'Escolha um recipiente',
      esgotado: 'Esgotado',
      estoque: 'estoque',
      gratuito: 'Gratuito',
      guardarEm: 'Guardar em',
      livre: 'livre',
      moedasInsuficientes: 'Moedas insuficientes',
      nenhumaMoeda: 'nenhuma moeda',
      oMestreAindaNao: 'O mestre ainda não disponibilizou itens à venda',
      ocupa: 'Ocupa',
      outros: 'Outros',
      precisaEspacoTipo: 'Precisa de {n} de espaço {tipo}, livre {livre}',
      precisaLivre: 'precisa de {n} livre',
      precoUnitario: 'Preço unitário',
      ptBr: 'pt-BR',
      quantidade: 'Quantidade',
      recipientePrecisaLivre: 'Recipiente precisa de {n}, livre {livre}',
      semRecipienteCompativelCompre: 'Sem recipiente compatível — compre um antes',
      soRestam: 'Só {n} restante(s)',
      suasMoedasNaoFecham: 'Suas moedas não fecham o valor exato (sem troco)',
      tipoLiquido: 'líquido',
      tipoSolido: 'sólido',
      todos: 'Todos',
      totalQtd: 'Total ({n})',
      voceTem: 'Você tem',
      motivos: {
        sem_historia: 'Sem história para este personagem',
        item_nao_listado: 'Item não está mais à venda',
        item_nao_existe: 'Item não encontrado',
        estoque_insuficiente: 'Estoque esgotado',
        moedas_insuficientes: 'Moedas insuficientes',
        moedasInsuficientesCusto: 'Moedas insuficientes (custo: {custo} latão)',
        espaco_insuficiente: 'Espaço insuficiente',
        espacoInsuficienteDet: 'Espaço insuficiente (precisa {ocupa}, livre {livre})',
        recipiente_obrigatorio: 'Consumíveis e moedas precisam ir dentro de um recipiente',
        moedas_nao_fecham: 'Suas moedas não fecham o valor exato (sem troco)',
        recipiente_invalido: 'Recipiente inválido',
        tipo_incompativel: 'O recipiente não aceita esse tipo de item',
        pj_nao_encontrado: 'Personagem não encontrado',
        quantidade_invalida: 'Quantidade inválida',
      },
    },
    batalha: {
      verboAtacar: 'Atacar',
      verboResistir: 'Resistir',
      verboUsar: 'Usar',
      jaRolouContinueEm: 'Já rolou — continue em {v}.',
      statusAtivo: 'Ativo',
      statusPassou: 'Passou',
      statusDesmaiado: 'Desmaiado',
      statusMorto: 'Morto',
      statusDesistiu: 'Desistiu',
      seuStatusPassando: 'Seu status: {status} — passando a vez…',
      abrir: 'Abrir',
      absurdoRoleNovamentePara: '⚠ Absurdo — role novamente para o efeito crítico no alvo.',
      acao: 'Ação',
      alvo: 'Alvo',
      /* ── Aba Apoio (01/09/2026): magias que alteram velocidade ──
         ateOFimDa e rodadas já existiam neste bloco e são reaproveitadas. */
      apoio: 'Apoio',
      alvoResistiu: 'O alvo resistiu — o efeito não pegou.',
      avisoConcentracao: 'Enquanto sustenta esta magia você não pode fazer mais nada. Atacar, usar item, andar ou levar dano na Energia Física quebra a concentração.',
      concentracao: 'Concentração',
      efeito: 'Efeito',
      magiaDeApoio: 'Magia',
      nivel: 'nível',
      porRodadas: 'por {n} rodadas',
      semMagiasDeApoio: 'Este combatente não conhece magias de apoio.',
      usar1Pa: 'Usar (1 PA)',
      velocidade: 'de velocidade',
      alvoNoD20: 'Alvo no d20',
      aplicadoJunto: '×{qtd}, aplicado junto',
      aplicar: 'Aplicar',
      arma: 'Arma',
      ateOFimDa: 'até o fim da batalha',
      ativa: 'Ativa',
      ausente: 'ausente',
      auto: 'auto',
      autoDano: ' · auto-dano',
      batalha: 'Batalha',
      batalhaEmAndamentoRodada: 'Batalha em andamento · rodada {rodada}',
      batalhaEmMontagem: 'Batalha em montagem',
      batalhas: 'Batalhas',
      cancelar: 'Cancelar',
      carregandoBatalha: 'Carregando batalha…',
      carregandoBatalhas: 'Carregando batalhas…',
      cliqueParaRemover: 'clique para remover',
      coluna: 'Coluna',
      colunaDeAcao: 'Coluna de Ação',
      colunaDeAcao7: 'Coluna de Ação (-7…50)',
      concluaARolagemPendente: 'Conclua a rolagem pendente primeiro',
      concluir: 'Concluir',
      confirmar: 'Confirmar',
      crU00edticoPulaEh: 'cr\\u00edtico (pula EH)',
      criando: 'Criando…',
      criarBatalha: 'Criar batalha',
      criaturas: 'Criaturas',
      critico: ' · crítico!',
      critico2: ' · crítico',
      criticoAlvo: 'Crítico — alvo',
      criticoEmSiMesmo: 'Crítico em si mesmo',
      criticoNoAlvo: 'Crítico no alvo',
      cura: 'Cura',
      dano: 'Dano',
      dano2: 'dano',
      dano3: 'dano',
      danoRodada: 'dano/rodada',
      // Nome por extenso das pools. Os mesmos rótulos que a Ficha usa: o
      // modal de edição mostra o nome inteiro no título, a barra do card
      // continua com a sigla.
      poolNome: { ef: 'Energia Física', eh: 'Energia Heroica', ar: 'Armadura', karma: 'Karma' },
      // VB/PA/DF viraram ícone no card (03/09/2026): a sigla que servia de
      // rótulo virou tooltip, e como tooltip ela tem que ser a palavra
      // inteira — "PA" não explica um raio na tela.
      statNome: { vb: 'Velocidade', pa: 'Ações', df: 'Defesa' },
      venenoDireto: 'Dano direto na Energia Física — ignora Armadura e Energia Heroica.',
      venenoTotal: 'no total',
      defesaResist120: 'Defesa / Resist. (1-20)',
      desmarcarTodos: 'Desmarcar todos',
      df: 'DF',
      eASuaVez: 'É a sua vez',
      eAVezDe: 'É a vez de {nome}',
      empate: 'Empate',
      empateRoleDeNovo: 'Empate — role de novo',
      empateRoleDeNovo2: 'Empate — role de novo',
      empateRoleOD20: 'Empate — role o d20 de novo.',
      encerrada: 'Encerrada',
      encerrar: 'Encerrar',
      encerrar2: 'Encerrar',
      encerrarArquivaOLog: 'Encerrar arquiva o log e remove esta batalha. Os PJs ficam na ficha exatamente como saíram do combate:',
      envenenado: 'Envenenado',
      erra: 'erra',
      errou: 'Errou',
      essaEAHora: 'Essa é a hora de escolher quem participará da batalha. Selecione os personagens dos jogadores e as criaturas que farão parte do confronto. Após definir os combatentes, tudo estará pronto para iniciar o combate e acompanhar cada turno da batalha.',
      estagio: 'Estágio',
      esteLutadorNaoTem: 'Este lutador não tem habilidades.',
      esteLutadorNaoTem2: 'Este lutador não tem técnicas.',
      excluir: 'Excluir',
      expandirRecolherBarrasDe: 'Expandir/recolher barras de ',
      falhaAoSalvar: 'Falha ao salvar',
      falhaCriticaRoleNovamente: '⚠ Falha Crítica — role novamente para o efeito em si mesmo.',
      falhaCriticaSiMesmo: 'Falha Crítica — si mesmo',
      falhaMotivo: 'Falha: {motivo}',
      feridoS: 'ferido(s)',
      filtrar: 'Filtrar…',
      foraDaFaixa: 'Fora da faixa — será salvo como',
      forcaDeAtaque: 'Força de Ataque',
      forcaDeAtaque1: 'Força de Ataque (1-20)',
      forcaDeDefesa: 'Força de Defesa',
      fracasso: 'Fracasso',
      habilidade: 'Habilidade',
      iniciando: 'Iniciando…',
      iniciar: 'Iniciar',
      inverterSelecao: 'Inverter seleção',
      item: 'Item',
      jogadores: 'Jogadores',
      karmaInsuficiente: 'Karma insuficiente',
      magia: 'Magia',
      maisUmaDeCada: 'Mais uma de cada',
      montagem: 'Montagem',
      mortoS: 'morto(s)',
      mudarEstado: 'Mudar estado',
      naoResistiu: 'Não resistiu',
      nenhumVinculadoAEsta: 'Nenhum vinculado a esta história',
      nenhuma: '— nenhuma —',
      nenhumaBatalhaNestaHistoria: 'Nenhuma batalha nesta história ainda.',
      novaBatalha: 'Nova batalha',
      novaRodada: 'Nova Rodada',
      pa: 'PA',
      participantes: 'participantes',
      passar: 'Passar',
      persistemComEf0: 'persistem com EF=0',
      pjsFeridosMantemAs: 'PJs ficam com as pools e condições do fim do combate',
      pool: 'Pool',
      ptBr: 'pt-BR',
      quantidade: 'Quantidade',
      resisteSeD20Alvo: 'resiste se d20 > alvo',
      resistencia: 'Resistência',
      resistenciaFisica: 'Resistência Física',
      resistenciaMagica: 'Resistência Mágica',
      resistiu: 'Resistiu',
      rodada: 'Rodada',
      rodadaSRestantes: 'rodada(s) restantes',
      rodadas: 'rodadas',
      rolagem: 'Rolagem: ',
      rolandoDadoPara: 'Rolando dado para ',
      rolarD20: 'Rolar d20',
      rolarD20DeCritico: 'Rolar d20 de crítico',
      rolarDeNovo: 'Rolar de novo',
      selecionarTodos: 'Selecionar todos',
      semAcoesDeCombate: 'Sem ações de combate disponíveis para este lutador.',
      semAlvosValidos: 'Sem alvos válidos.',
      semAtacarBloqueado: 'Este lutador está impedido de atacar agora.',
      semEfeitoMecanicoSo: 'Sem efeito mecânico — só consome o item.',
      semItensConsumiveisNo: 'Sem itens consumíveis no inventário.',
      semPaDisponivel: 'Sem PA disponível',
      semResultados: 'Sem resultados',
      semTecnicasBloqueado: 'Este lutador está impedido de usar técnicas agora.',
      seuStatus: 'Seu status: {status}',
      sucesso: 'Sucesso',
      tecnica: 'Técnica',
      tecnicaOpcional: 'Técnica (opcional)',
      // i18n-sync (Fase 3.3): as 6 abaixo vieram de ternárias `isEn ? … : …`
      // inline na aba Técnica do console de batalha — texto pt idêntico ao
      // que já existia, só movido pra cá (tecnica-aba.test.jsx casa por
      // texto pt e não pode quebrar). As 3 com {} usam interpolate().
      tecnicaAliadosRotulo: 'Aliados ({atual}/{max})',
      tecnicaExigeArma: 'Exige arma do grupo: {grupo}.',
      tecnicaExigeArmadura: 'Exige armadura do grupo: {grupo}.',
      tecnicaGratuitaJaUsada: 'Já ativou uma técnica gratuita nesta rodada.',
      tecnicaUsoUnicoJaUsada: 'Já usada nesta batalha (uso Único).',
      tecnicaParcialIgnoraArmadura: 'A metade que ignora a armadura ainda não é automática — aplique na mão.',
      todosOsPjsNo: 'Todos os PJs no máximo.',
      tudoProntoParaO: 'Tudo pronto para o início da batalha. A ordem de ação, ou iniciativa, é determinada pela velocidade de cada participante.',
      umaDeCada: 'Uma de cada',
      valor: 'valor',
      veneno: 'Veneno',
      voce: ' (você)',
      voltarAFicha: 'Voltar à ficha',
      voltarAsHistorias: 'Voltar às histórias',
      zerarTodas: 'Zerar todas',
    },
  },
  en: {
    convites: {
      mng: {
        titulo: 'Manage invites',
        fechar: 'Close',
        gerando: 'Generating…',
        novoConvite: 'New invite',
        descricao: 'Generate codes to invite players to the adventure "{tituloHistoria}".',
        carregando: 'Loading…',
        vazio: "You haven't generated any invitations yet.",
        uiKitAusente: 'UI kit not loaded (ui-bridge).',
        copiar: 'Copy',
        copiado: 'Copied',
        reativar: 'Reactivate',
        remover: 'Remove',
        falhouComMotivo: 'Failed: {motivo}',
        falhouDesconhecido: 'unknown',
      },
      status: {
        ativo: 'Active',
        usado: 'Used',
        revogado: 'Revoked',
        expirado: 'Expired',
      },
      jogador: {
        digiteCodigoPrimeiro: 'Enter a code first',
        semPersonagem: "You haven't created a character yet — you need to create one before accepting the invitation",
        instrucao: 'To join an adventure, paste the code the Game Master shared with you into the field below.',
        continuar: 'Continue',
        escolherPj: 'Code: {codigo}. Choose which character to link to this story:',
        voltar: 'Back',
        aceitando: 'Accepting…',
        aceitarConvite: 'Accept invite',
        conviteAceito: 'Invite accepted!',
        sucesso: 'Your character {pjNome} is now part of {historiaTitulo}.',
        aceitarOutro: 'Accept another',
        dataADefinir: 'Date to be set',
      },
      motivo: {
        codigo_invalido: 'Invalid code',
        convite_expirado: 'Invite expired',
        convite_ja_usado: 'Invite already used',
        convite_revogado: 'Invite was revoked by the Master',
        pj_nao_pertence: 'That character is not yours',
        pj_nao_encontrado: 'Character not found',
        pj_ja_vinculado: 'That character is already in this table',
        nao_autenticado: 'Session expired — sign in again',
      },
      aceitarModal: {
        concluir: 'Done',
        entrarMesa: 'Join a table',
        depois: 'Later',
        convitePrompt: 'Got an invite code from a Game Master? Use it to bring {nomePj} into a story.',
      },
    },
    historias: {
      lista: {
        carregando: 'Loading stories…',
        erroTabela: "Make sure the 'historias' table exists in Supabase.",
        comecarAventura: 'Start a new adventure when you are ready',
        limitePlanoFree: "You've reached the story limit for the free plan — upgrade now.",
        novaHistoria: 'New story',
      },
      card: {
        batalhas: 'Battles',
        convites: 'Invites',
        lore: 'Lore',
        loreTip: 'Lore (NPCs, Kingdoms, Cities)',
        lojaTip: 'Shop ({qtd})',
        loja: 'Shop',
        editar: 'Edit',
        excluir: 'Delete',
        protagonistas: 'Protagonists',
      },
      excluirModal: {
        titulo: 'Delete?',
        confirmar: 'Delete',
        aviso: 'The story "{titulo}" will be permanently removed.',
      },
      loja: {
        shop: 'Shop',
        shopSub: 'Items for sale to players of {titulo}.',
        catalog: 'Catalog',
        catalogSub: 'Search…',
        empty: 'Pick from the catalog',
        none: 'No items match.',
        loading: 'Loading catalog…',
        price: 'Price',
        stock: 'Stock',
        remove: 'Remove',
        cancel: 'Cancel',
        save: 'Save',
        saving: 'Saving…',
        search: 'Search…',
        allGroups: 'All groups',
        clear: 'Clear',
        inDesc: 'in description',
        inOrig: 'in origin',
        inDetails: 'in details',
        catalogPrice: 'Catalog price',
        addToShop: 'Add',
        origin: 'Origin',
        liquid: 'liquid',
        magic: 'magic',
        moedaOuro: 'g',
        moedaPrata: 's',
        moedaCobre: 'c',
        moedaLatao: 'b',
        gratis: 'free',
        inShopSingular: '{n} item in shop',
        inShopPlural: '{n} items in shop',
        showing: '{n} of {total}',
        paginaPrimeira: 'First page',
        paginaAnterior: 'Previous',
        paginaProxima: 'Next',
        paginaUltima: 'Last page',
        paginaInfo: 'Page {atual} of {total}',
      },
      novaModal: {
        editarTitulo: 'Edit story',
        novaTitulo: 'New story',
        salvando: 'Saving…',
        salvar: 'Save',
        criar: 'Create',
        titulo: 'Title',
        tituloPlaceholder: 'The Shadow of Verrogar',
        reino: 'Realm',
        reinoPlaceholder: 'Kingdom of Verrogar',
        dataInicio: 'Start date',
        dataInicioJogo: 'Start in-game date',
        criaturas: 'Creatures',
        selecionadas: 'selected',
        semCriaturas: 'No creatures in the bestiary yet',
      },
    },
    lore: {
      form: {
        nome: 'Name',
        descricao: 'Description',
        imagem: 'Image (URL, optional)',
        deus: 'Deity',
        raca: 'Race',
        localizacao: 'Location',
        cidadeNatal: 'Hometown',
        classeSocial: 'Social Class',
        idade: 'Age',
        familia: 'Family',
        relacao: 'Relationship',
        status: 'Status',
        rumores: 'Rumors',
        icone: 'Icon (URL, optional)',
        governo: 'Government',
        cultura: 'Culture',
        historiaRecente: 'Recent History',
        reino: 'Realm',
        populacao: 'Population',
        capitalDoReino: "Is the realm's capital",
      },
    },
    inventario: {
      abaterEPreparar: 'Slaughter and process {nome}? You will receive {qtd}× {consumivel}.',
      abrindoAsAlgibeiras: 'Loading inventory…',
      aprendendo: 'Learning…',
      aprender: 'Learn',
      armaduras: 'Armor',
      armazenar: 'Store',
      buscar: 'Search',
      cancelar: 'Cancel',
      capacidade: 'Capacity',
      cargaPesada: 'Heavy load',
      carregando: 'Carried',
      confiraSeATabela: 'Make sure tables \'itens\' and column \'inventario\' exist in Supabase.',
      confirmar: 'Confirm',
      cuidadoEssaAcaoE: 'Caution, this action is irreversible.',
      deMax: 'of {max}',
      descartar: 'Descart',
      desequipar: 'Unequip',
      despir: 'Take off',
      destruirEsteItemPermanentemente: 'Destroy this item permanently?',
      destruirItem: 'Destroy item',
      detalhes: 'Details',
      efeito: 'Effect',
      enviando: 'Sending…',
      equipar: 'Equip',
      esteItemNaoE: 'This item is not a spell scroll.',
      falhaAoSalvar: 'Save failed',
      gratis: 'Free',
      liquidos: 'liquids',
      magiaNaoEncontradaNo: 'Spell not found in the catalog.',
      max: 'Max',
      mesaUsouItem: '{nome} used {item}',
      moedas: 'Coins',
      naoFoiPossivelAprender: 'Could not learn the spell.',
      nenhumRecipienteCompativelNo: 'No compatible container in inventory',
      nivelDeMagiaInvalido: 'Invalid spell level on the scroll.',
      oNivelDaMagia: 'Spell level exceeds your character\'s stage.',
      ocupadoPorEquip: '{slot} occupied by gear.',
      outros: 'Other',
      pergaminhoNaoEncontradoNo: 'Scroll not found in your inventory.',
      personagemNaoEncontrado: 'Character not found.',
      peso: 'Weight',
      pontosDeMagiaInsuficientes: 'Not enough magic points.',
      precisaMaosLivres: 'Needs {maos} free hand(s) ({livres} free).',
      preparar: 'Prepare',
      prepararAnimal: 'Prepare animal',
      proibidoParaRaca: 'Forbidden for {raca}.',
      pt: 'en',
      ptBr: 'en-US',
      salvando: 'Saving…',
      salvo: 'Saved ✓',
      semSlotDefinido: 'No slot defined.',
      semSlotDefinidoPara: 'No slot defined for this item.',
      simDestruir: 'Yes, destroy',
      simPreparar: 'Yes, prepare',
      simUsar: 'Yes, use',
      slotCheio: 'Slot full ({usado}/{max}).',
      slotOcupado: 'Slot {slot} occupied.',
      sobrecarregado: 'Overloaded!',
      solidos: 'solids',
      suaProfissaoNaoPode: 'Your class cannot learn this spell.',
      tituloArmazenar: 'Store {nome}',
      tituloDestruir: 'Destroy {nome}',
      tituloRetirar: 'Take out {nome}',
      tituloUsar: 'Use {nome}',
      todos: 'All',
      transferir: 'Transfer',
      usar: 'Use',
      usarEsteItem: 'Use this item?',
      usarItem: 'Use item',
      vestimentas: 'Worn',
      vestir: 'Wear',
      voceJaTemEssa: 'You already know this spell at this level or higher.',
      voceNaoEstaAutenticado: 'You are not signed in.',
      voceNaoTemNenhum: 'You have no possessions.',
      vocePrecisaAprenderO: 'You must learn the previous level first.',
      zerar: 'Reset',
    },
    loja: {
      abraFicha: 'Open a character\'s sheet to enter its shop',
      abrindoALoja: 'Opening the shop…',
      absorcao: 'Absorb',
      alcance: 'Range',
      armazena: 'Stores',
      buscar: 'Search',
      cancelar: 'Cancel',
      comprar: 'Buy',
      comprou: 'Bought {qtd} {nome}.',
      dano: 'Damage',
      de: 'of',
      e: ' and ',
      efeito: 'Effect',
      escolhaUmRecipiente: 'Choose a container',
      esgotado: 'Out of stock',
      estoque: 'stock',
      gratuito: 'Free',
      guardarEm: 'Store in',
      livre: 'free',
      moedasInsuficientes: 'Not enough coin',
      nenhumaMoeda: 'no coins',
      oMestreAindaNao: 'The Game Master has not listed any items yet',
      ocupa: 'Takes',
      outros: 'Other',
      precisaEspacoTipo: 'Needs {n} {tipo} space, free {livre}',
      precisaLivre: 'needs {n} free',
      precoUnitario: 'Unit price',
      ptBr: 'en-US',
      quantidade: 'Quantity',
      recipientePrecisaLivre: 'Container needs {n}, free {livre}',
      semRecipienteCompativelCompre: 'No compatible container — buy one first',
      soRestam: 'Only {n} left',
      suasMoedasNaoFecham: 'Your coins can’t make the exact price (no change)',
      tipoLiquido: 'liquid',
      tipoSolido: 'solid',
      todos: 'All',
      totalQtd: 'Total ({n})',
      voceTem: 'You have',
      motivos: {
        sem_historia: 'No story for this character',
        item_nao_listado: 'Item not listed in this shop',
        item_nao_existe: 'Item not found',
        estoque_insuficiente: 'Out of stock',
        moedas_insuficientes: 'Not enough coin',
        moedasInsuficientesCusto: 'Not enough coin (cost: {custo} brass)',
        espaco_insuficiente: 'Not enough space',
        espacoInsuficienteDet: 'Not enough space (needs {ocupa}, free {livre})',
        recipiente_obrigatorio: 'Consumables and coins must go inside a container',
        moedas_nao_fecham: 'Your coins can’t make the exact price (no change given)',
        recipiente_invalido: 'Invalid container',
        tipo_incompativel: 'Container does not accept this item type',
        pj_nao_encontrado: 'Character not found',
        quantidade_invalida: 'Invalid quantity',
      },
    },
    batalha: {
      verboAtacar: 'Attack',
      verboResistir: 'Resist',
      verboUsar: 'Use',
      jaRolouContinueEm: 'Already rolled — continue to confirm.',
      statusAtivo: 'Active',
      statusPassou: 'Passed',
      statusDesmaiado: 'Downed',
      statusMorto: 'Dead',
      statusDesistiu: 'Withdrew',
      seuStatusPassando: 'Your status: {status} — passing turn…',
      abrir: 'Open',
      absurdoRoleNovamentePara: '⚠ Absurd — roll again for critical effect on target.',
      acao: 'Action',
      alvo: 'Target',
      /* ── Support tab (2026-09-01): spells that change speed ──
         ateOFimDa and rodadas already existed in this block; reused. */
      apoio: 'Support',
      alvoResistiu: 'The target resisted — the effect did not land.',
      avisoConcentracao: 'While sustaining this spell you cannot do anything else. Attacking, using an item, moving or taking Physical Energy damage breaks concentration.',
      concentracao: 'Concentration',
      efeito: 'Effect',
      magiaDeApoio: 'Spell',
      nivel: 'level',
      porRodadas: 'for {n} rounds',
      semMagiasDeApoio: 'This combatant knows no support spells.',
      usar1Pa: 'Use (1 AP)',
      velocidade: 'speed',
      alvoNoD20: 'Target on d20',
      aplicadoJunto: '×{qtd}, applied together',
      aplicar: 'Apply',
      arma: 'Weapon',
      ateOFimDa: 'until battle ends',
      ativa: 'Active',
      ausente: 'missing',
      auto: 'auto',
      autoDano: ' · self-damage',
      batalha: 'Battle',
      batalhaEmAndamentoRodada: 'Battle in progress · round {rodada}',
      batalhaEmMontagem: 'Battle in setup',
      batalhas: 'Battles',
      cancelar: 'Cancel',
      carregandoBatalha: 'Loading battle…',
      carregandoBatalhas: 'Loading battles…',
      cliqueParaRemover: 'click to remove',
      coluna: 'Col',
      colunaDeAcao: 'Action column',
      colunaDeAcao7: 'Action column (-7…50)',
      concluaARolagemPendente: 'Finish the pending roll first',
      concluir: 'Done',
      confirmar: 'Confirm',
      crU00edticoPulaEh: 'critical (skips EH)',
      criando: 'Creating…',
      criarBatalha: 'Create battle',
      criaturas: 'Creatures',
      critico: ' · critical!',
      critico2: ' · critical',
      criticoAlvo: 'Critical — target',
      criticoEmSiMesmo: 'Critical on self',
      criticoNoAlvo: 'Critical on target',
      cura: 'Heal',
      dano: 'Damage',
      dano2: 'damage',
      dano3: 'dmg',
      danoRodada: 'dmg/round',
      poolNome: { ef: 'Physical Energy', eh: 'Heroic Energy', ar: 'Armor', karma: 'Karma' },
      statNome: { vb: 'Speed', pa: 'Actions', df: 'Defense' },
      venenoDireto: 'Direct Physical Energy damage — ignores Armor and Heroic Energy.',
      venenoTotal: 'in total',
      defesaResist120: 'Defense / Resist. (1-20)',
      desmarcarTodos: 'Deselect all',
      df: 'DF',
      eASuaVez: 'It\'s your turn',
      eAVezDe: 'It\'s {nome}\'s turn',
      empate: 'Tie',
      empateRoleDeNovo: 'Tie — roll again',
      empateRoleDeNovo2: 'Tie — re-roll',
      empateRoleOD20: 'Tie — roll the d20 again.',
      encerrada: 'Ended',
      encerrar: 'End',
      encerrar2: 'Withdraw',
      encerrarArquivaOLog: 'Ending archives the log and removes this battle. PCs keep on their sheet exactly what they left combat with:',
      envenenado: 'Poisoned',
      erra: 'miss',
      errou: 'Miss',
      essaEAHora: 'Choose who will take part in the battle. Select the player characters and creatures that will join the confrontation. Once the combatants are set, everything will be ready to start combat and track each turn.',
      estagio: 'Stage',
      esteLutadorNaoTem: 'This fighter has no skills.',
      esteLutadorNaoTem2: 'This fighter has no techniques.',
      excluir: 'Delete',
      expandirRecolherBarrasDe: 'Toggle pools for ',
      falhaAoSalvar: 'Failed to save',
      falhaCriticaRoleNovamente: '⚠ Critical Failure — roll again for self-damage effect.',
      falhaCriticaSiMesmo: 'Critical Failure — self',
      falhaMotivo: 'Failed: {motivo}',
      feridoS: 'wounded',
      filtrar: 'Filter…',
      foraDaFaixa: 'Out of range — will be saved as',
      forcaDeAtaque: 'Attack force',
      forcaDeAtaque1: 'Attack force (1-20)',
      forcaDeDefesa: 'Defense force',
      fracasso: 'Failure',
      habilidade: 'Skill',
      iniciando: 'Starting…',
      iniciar: 'Start',
      inverterSelecao: 'Invert selection',
      item: 'Item',
      jogadores: 'Players',
      karmaInsuficiente: 'Not enough karma',
      magia: 'Spell',
      maisUmaDeCada: 'Add one more of each',
      montagem: 'Setup',
      mortoS: 'dead',
      mudarEstado: 'Change state',
      naoResistiu: 'Not resisted',
      nenhumVinculadoAEsta: 'None linked to this story',
      nenhuma: '— none —',
      nenhumaBatalhaNestaHistoria: 'No battles yet for this story.',
      novaBatalha: 'New battle',
      novaRodada: 'New Turn',
      pa: 'AP',
      participantes: 'participants',
      passar: 'Pass',
      persistemComEf0: 'persist with EF=0',
      pjsFeridosMantemAs: 'PCs keep the pools and conditions they ended combat with',
      pool: 'Pool',
      ptBr: 'en-US',
      quantidade: 'Quantity',
      resisteSeD20Alvo: 'resists if d20 > target',
      resistencia: 'Resistance',
      resistenciaFisica: 'Physical Resistance',
      resistenciaMagica: 'Magic Resistance',
      resistiu: 'Resisted',
      rodada: 'Round',
      rodadaSRestantes: 'rounds left',
      rodadas: 'rounds',
      rolagem: 'Roll: ',
      rolandoDadoPara: 'Rolling die for ',
      rolarD20: 'Roll d20',
      rolarD20DeCritico: 'Roll critical d20',
      rolarDeNovo: 'Roll again',
      selecionarTodos: 'Select all',
      semAcoesDeCombate: 'No combat actions available for this actor.',
      semAlvosValidos: 'No valid targets.',
      semAtacarBloqueado: 'This fighter is blocked from attacking right now.',
      semEfeitoMecanicoSo: 'No mechanical effect — consumes the item only.',
      semItensConsumiveisNo: 'No consumable items in inventory.',
      semPaDisponivel: 'No AP left',
      semResultados: 'No results',
      semTecnicasBloqueado: 'This fighter is blocked from using techniques right now.',
      seuStatus: 'Your status: {status}',
      sucesso: 'Success',
      tecnica: 'Technique',
      tecnicaOpcional: 'Technique (optional)',
      // i18n-sync (Fase 3.3): espelha o bloco pt acima, mesmo conteúdo em inglês.
      tecnicaAliadosRotulo: 'Allies ({atual}/{max})',
      tecnicaExigeArma: 'Requires a weapon of group: {grupo}.',
      tecnicaExigeArmadura: 'Requires armor of group: {grupo}.',
      tecnicaGratuitaJaUsada: 'Already used a free technique this round.',
      tecnicaUsoUnicoJaUsada: 'Already used this battle (single use).',
      tecnicaParcialIgnoraArmadura: 'Armor-ignoring half is not automated yet — apply it manually.',
      todosOsPjsNo: 'All PCs at full pools.',
      tudoProntoParaO: 'Everything is ready for the battle to begin. The turn order, or initiative, is determined by each participants speed.',
      umaDeCada: 'One of each',
      valor: 'amount',
      veneno: 'Poison',
      voce: ' (you)',
      voltarAFicha: 'Back to sheet',
      voltarAsHistorias: 'Back to stories',
      zerarTodas: 'Remove all',
    },
  },
};

window.COPY = COPY;

Object.assign(window, { COPY });