/* ============================================================
   COPY — Strings de i18n (PT-BR / EN) da landing page
   ============================================================
   Originalmente em app.jsx [00]. Extraído na Fase 0 da refatoração.
   Acessível como `COPY` (global) ou `window.COPY` (para o painel
   de tweaks ou outros consumidores externos).
   ============================================================ */
/* ============================== [00] COPY / i18n ============================== */

// PT-BR and EN copy
const COPY = {
  pt: {
    nav: { features: 'Recursos', pricing: 'Planos', faq: 'Perguntas', signin: 'Entrar' },
    cta_main: 'Forjar minha mesa',
    cta_ghost: 'Ver os planos',
    hero: {
      eyebrow: 'Plataforma de mesa de RPG para Mestres & Jogadores',
      h1_pre: 'Sua mesa nunca mais',
      h1_accent: 'será a mesma',
      sub: 'Crie campanhas, fichas, personagens, ambientação e muito mais. Tudo isso em apenas uma só plataforma — em qualquer sistema de RPG.',
      micro: ['Acesso imediato', 'Sem cartão', 'Plano grátis pra sempre'],
    },
    opening: {
      eyebrow: 'Capítulo I — A Promessa',
      h: 'Toda mesa começa com uma promessa: essa noite vai ser épica!',
      p1: 'Mas quando a hora chega: alguém esqueceu a ficha, o novato não sabe as regras ou o mestre não preparou a sessão. E mesmo quando tudo isso não acontece, você sente que ainda falta alguma coisa.',
      p2: 'De mestre para mestre, de jogador para jogador: o Menestrel nasceu para resolver todos esses problemas! Aqui é onde mestre e jogadores se encontram, com tudo que a mesa precisa sob o mesmo teto: fichas, personagens, criaturas, ambientação, combate por turno, inventário e loja.',
      p3: 'Você escolhe o sistema que quer jogar, e o Menestrel cuida do resto.',
    },
    pain: {
      eyebrow: 'Capítulo II — As Sombras',
      h1_accent: 'Você ama RPG,',
      h: 'mas não tem tanto tempo como antigamente?',
      list: [
        'Você já passou horas escrevendo um vilão que o grupo matou em 2 turnos?',
        'Você já abriu 5 abas diferentes do navegador só para narrar uma única sessão — ficha aqui, mapa ali, regra do livro acolá?',
        'Você já perdeu uma campanha porque o grupo não conseguiu marcar presencial e ninguém quis migrar para aquela ferramenta complicada?',
        'Você já desistiu de mestrar um sistema novo porque as regras eram um labirinto?',
        'Você já viu jogador abandonar a mesa porque "tá difícil acompanhar"?',
        'Você já sentiu que, em vez de contar uma história, você virou um administrador de planilhas?',
      ],
      quote: 'A mesa deve ser o lugar onde a imaginação corre solta. Pare de ficar discutindo regras ou olhando para tabuleiros digitais.',
    },
    solution: {
      eyebrow: 'Capítulo III — A Solução',
      h: 'O Menestrel é o bardo invisível da sua mesa',
      p1: 'Enquanto você foca em contar a história, ele cuida do que rouba seu tempo: organiza as fichas, gerencia personangens e criaturas, controla turnos de combate, registra inventário e abriga a ambientação do seu mundo.',
      p2: 'E o mais importante: funciona com qualquer sistema. Você customiza e o Menestrel se adapta.',
      card_h: 'Sistemas suportados',
      card_p: 'Tudo online e sincronizado — é a sua mesa à distância sem perder o sangue, o suor e a fumaça da taverna.',
      systems: ['D&D 5e', 'Tagmar 3', 'Tormenta20', 'Pathfinder', 'Call of Cthulhu', 'Vampiro: A Máscara', 'GURPS'],
      custom: 'Seu sistema',
      tree: [
        { label: 'Organiza', items: ['fichas', 'campanhas', 'ambientação'] },
        { label: 'Gerencia', items: ['personagens', 'criaturas', 'bestiário'] },
        { label: 'Controla', items: ['turnos de combate', 'energias e condições', 'danos e magias'] },
        { label: 'Registra', items: ['inventário', 'loja', 'cofre de moedas'] },
      ],
    },
    benefits: {
      eyebrow: 'Capítulo IV — Os Dons',
      h: 'O que muda quando o Menestrel chega à mesa',
      sub: 'Temos pelo menos oito ganhos concretos pra mestres e jogadores. Não é promessa vaga e nem milagre, nosso sistema é constantemente testado por quem ama e joga RPG há muitos anos.',
      stages: [
        { badge: 'Preparação', h: 'Prepare a sessão em minutos, não em horas.', checks: ['Personagens e criaturas em minutos', 'Fichas que não somem nunca'] },
        { badge: 'A Mesa', h: 'Toda a mesa em uma aba só.', checks: ['Fichas, mapas, loja e inventário', 'Adeus ao caos das 12 abas'] },
        { badge: 'Combate', h: 'Combate por turno sem dor de cabeça.', checks: ['Turnos, energias e condições', 'Danos e magias calculados pra você'] },
        { badge: 'Qualquer lugar', h: 'A mesa continua, pra onde a vida levar.', checks: ['Web em qualquer dispositivo', 'Qualquer sistema, com a sua cara'], featured: true, cta: 'Forjar minha mesa' },
      ],
      list: [
        { icon: 'Scroll', t: 'Conte histórias sem perer tempo com planilhas.', d: 'Você volta a ser o mestre e a narrativa fica mais evidente.' },
        { icon: 'Tower', t: 'Toda a mesa em uma aba só.', d: 'Fichas, personagens, criaturas, mapa, combate, loja, inventário. Acaba o caos das 12 abas abertas.' },
        { icon: 'Compass', t: 'Qualquer sistema fica com a sua cara.', d: 'Customização total pra rodar qualquer sistema sem amarras.' },
        { icon: 'Sword', t: 'Combate por turno sem dor de cabeça.', d: 'Cálculo de turnos, de energias, de condições, danos, magias — o sistema controla tudo para você.' },
        { icon: 'Compass', t: 'Jogue de qualquer lugar.', d: 'O grupo se mudou, o amigo trabalha fora, a filha do mestre nasceu? A mesa continua pela web em qualquer dispositivo!' },
        { icon: 'Skull', t: 'Personagens e criaturas em minutos.', d: 'Crie um vilão memorável antes da próxima sessão em poucos minutos.' },
        { icon: 'Scroll', t: 'Fichas que não somem nunca.', d: 'Aquele personagem de 3 anos atrás? Tá lá esperando para salvar o mundo mais uma vez.' },
        { icon: 'Flame', t: 'Simples na superfície mas profundo por dentro.', d: 'Um iniciante roda a primeira mesa em minutos e o veterano encontra a customização suficiente pra qualquer mesa presencial.' },
      ],
    },
    social: {
      eyebrow: 'Capítulo V — A Guilda',
      h: 'A taverna está enchendo',
      stats: [
        { n: '847', l: 'Mesas forjadas' },
        { n: '1.420', l: 'Mestres & jogadores' },
        { n: '4.8', l: 'Avaliação' },
      ],
      testimonials: [
        { q: 'Eu preparava a sessão por quase 6 horas. Agora preparo em 40 minutos. Voltei a ter vida fora da mesa — e a mesa ficou melhor.', who: 'Rafael "Corvus"', role: 'Mestre de D&D 5e há 8 anos' },
        { q: 'Sou jogadora, não sou de tecnologia. Em 5 minutos eu já tava criando minha ficha. Sem manual, sem amigo me ensinando. Funcionou.', who: 'Marina Aguiar', role: 'Jogadora de Tagmar 3há 3 anos' },
        { q: 'Migramos a campanha de outra plataforma em uma tarde. O grupo nem reclamou — o que nunca acontece. Esse é o ponto.', who: 'Diego "Khorn"', role: 'Mestre, Grupo Cinco Lâminas' },
      ],
    },
    plans: {
      eyebrow: 'Capítulo VI — A Oferta',
      h: 'Você escolhe o tamanho da aventura',
      free: {
        tag: 'Plano Básico',
        name: 'Gratuito',
        price: 'R$ 0',
        unit: '/pra sempre',
        group: '',
        features: [
          'Crie até 5 fichas de personagem',
          'Crie até 3 campanhas',
          'Sistema de combate por turno',
          'Personagens e criaturas básicos',
          'Inventário e loja',
          'Acesso web em qualquer dispositivo',
        ],
        cta: 'Começar de graça',
      },
      pro: {
        tag: 'Plano Avançado',
        name: 'Lendário',
        price: 'R$ 9,90',
        unit: '/mês',
        group: 'Grupo até 5 pessoas — R$ 29,90/mês (menos de R$ 6 por pessoa)',
        features: [
          'Todas as funções do modo gratuito, sem limite',
          'Fichas, campanhas e personasgens ilimitados',
          'Ambientação avançada de mundo',
          'Suporte prioritário',
          'Todos os recursos futuros, sem custo extra',
          'Aplicativo para iOS e Android',
        ],
        cta: 'Quero ser Lendário',
      },
    },
    guarantee: {
      eyebrow: 'Garantia do Bardo',
      h: 'Plano Lendário grátis por 7 dias',
      p: 'Assine o plano Lendário e teste à vontade por 7 dias. Se o Menestrel não economizar seu tempo, se não fizer sua mesa fluir, se simplesmente não for pra você — devolvemos 100% do seu dinheiro.',
    },
    scarcity: {
      eyebrow: 'Lote Fundadores',
      h: 'Os primeiros 500 viram Membros Fundadores',
      p: 'Congele o preço de R$ 9,90/mês pra sempre (mesmo quando o preço subir), acesso antecipado a recursos novos, e o badge exclusivo de Fundador no perfil.',
      filled: 365,
      total: 500,
    },
    objections: {
      eyebrow: 'Capítulo VII — As Dúvidas',
      h: 'Já pensei nisso, mas...',
      list: [
        { q: 'Já uso Roll20, Foundry ou outra plataforma', a: 'A gente entende — e respeita. Mas o Menestrel não é mais uma ferramenta complexa que exige 3 horas de tutorial. É feito pra rodar a primeira mesa em minutos, sem virar técnico de software. Teste grátis e compare.' },
        { q: 'Papel e caneta sempre funcionou pra mim', a: 'E vai continuar funcionando! O Menestrel não substitui a magia da mesa física — ele resgata essa magia quando o grupo não pode estar junto. É pro dia que alguém se mudou, teve filho, mudou de turno. A campanha não morre.' },
        { q: 'Meu grupo não vai querer migrar', a: 'É de graça e não tem tem que instalar nada. Se em uma sessão alguém reclamar, é só voltar. Mas é raro voltar — porque o Menestrel desaparece durante o jogo.' },
        { q: 'Vai ficar caro a longo prazo', a: 'O plano grátis é grátis pra sempre. Se for assinar o Lendário em grupo, sai por menos de R$ 6 por pessoa por mês — menos que um café. Por uma mesa rodando sem fricção, todo mês.' },
      ],
    },
    faq: {
      eyebrow: 'Pergaminho de Perguntas',
      h: 'Perguntas Frequentes',
      list: [
        { q: 'Em que sistemas de RPG o Menestrel funciona?', a: 'Em qualquer um. D&D 5e, Tormenta20, Pathfinder, Call of Cthulhu, Vampiro: A Máscara, GURPS, sistemas próprios — você customiza fichas, regras e atributos do jeito que sua mesa joga.' },
        { q: 'Sou iniciante. Consigo usar?', a: 'Sim. O Menestrel foi feito pra quem nunca abriu uma plataforma de RPG digital antes. Cria sua primeira ficha em minutos. Sem manual de 200 páginas.' },
        { q: 'Sou mestre veterano com mesa homebrew. Consigo customizar do meu jeito?', a: 'Sim. A customização é total — você define atributos, perícias, regras, classes. O Menestrel se molda ao seu sistema, não o contrário.' },
        { q: 'Funciona no celular?', a: 'Sim. É web — roda em qualquer navegador, celular, tablet ou computador.' },
        { q: 'E se eu não gostar do plano Lendário?', a: 'Você tem 7 dias de garantia. Pediu reembolso, devolvemos 100%. Sem perguntas, sem burocracia.' },
        { q: 'Como funciona o plano em grupo (R$ 29,90)?', a: 'Você assina e libera acesso pra até 5 pessoas (mestre + 4 jogadores, ou 5 mestres, como preferir). Sai menos de R$ 6 por cabeça.' },
        { q: 'Posso cancelar quando quiser?', a: 'Pode. Sem multa. Sem ligação pra reter. Cancela no painel em 2 cliques.' },
        { q: 'Meus dados e fichas ficam salvos se eu cancelar?', a: 'Sim. Tudo fica salvo na sua conta. Se voltar um dia, sua mesa tá lá esperando.' },
      ],
    },
    final: {
      eyebrow: 'Último capítulo',
      h_a: 'Sua próxima campanha',
      h_b: 'já começou',
      p: 'Os personagens já existem, os vilões esperam, e o mundo só precisa de alguém que o conte. Pare de adiar. Pare de improvisar em 8 abas diferentes. A taverna abriu as portas. O bardo já afinou o alaúde.',
      cta: 'Forjar a Mesa',
      micro: 'Acesso imediato • Sem cartão • Grátis pra sempre',
      ps: 'Toda grande campanha começa com uma escolha pequena. Você pode continuar perdendo horas preparando mesas que cansam, ou começar a usar Menestrel grátis e ver, em uma única sessão, o que muda quando a gente cuida do sistema e você volta a contar a história.',
      pps: 'O plano Lendário tem 7 dias de garantia. Ou seja, você pode testar sem risco. E se aproveitar a fase de lançamento, paga R$ 9,90/mês pra sempre como Fundador e sua subscrição nunca vai aumentar.',
    },
    modal: {
      title: 'Forjar o Perfil',
      sub: 'Crie sua conta em poucos segundos.',
      consent: 'Concordo com a Política de Privacidade e com o tratamento dos meus dados conforme a LGPD.',
      close: 'Fechar',
    },
    footer: {
      tag: 'O bardo invisível da sua mesa.',
      links: ['Termos', 'Privacidade (LGPD)', 'Contato', 'Status'],
      copy: '© 2026 Menestrel. by Rossati.',
    },
    convites: {
      mng: {
        titulo: 'Gerenciar convites',
        fechar: 'Fechar',
        gerando: 'Gerando…',
        novoConvite: 'Gerar convite',
        descricao: 'Agora que sua aventura foi criada, é hora de convidar os jogadores. Compartilhe com eles o código gerado abaixo. Para participar, cada jogador deve primeiro criar um novo personagem. Depois disso, basta usar o código da aventura para entrar na sua mesa e começar a jornada.',
        carregando: 'Carregando…',
        vazio: 'Você ainda não gerou nenhum convite.',
        uiKitAusente: 'Kit de UI não carregado (ui-bridge).',
        copiar: 'Copiar',
        copiado: 'Copiado',
        reativar: 'Reativar',
        remover: 'Remover',
        falhouComMotivo: 'Falhou: {motivo}',
        falhouDesconhecido: 'desconhecido',
      },
      status: {
        ativo: 'Ativo',
        usado: 'Usado',
        revogado: 'Revogado',
        expirado: 'Expirado',
      },
      jogador: {
        digiteCodigoPrimeiro: 'Digite um código primeiro',
        semPersonagem: 'Você ainda não criou um personagem — é necessário criar um antes de aceitar o convite',
        instrucao: 'Para participar de uma aventura, cole o código que o mestre compartilhou com você no campo abaixo.',
        continuar: 'Continuar',
        escolherPj: 'Escolha qual personagem você quer vincular a esta história ({codigo}):',
        voltar: 'Voltar',
        aceitando: 'Aceitando…',
        aceitarConvite: 'Aceitar convite',
        conviteAceito: 'Convite aceito!',
        sucesso: 'Seu personagem {pjNome} agora faz parte de {historiaTitulo}.',
        aceitarOutro: 'Aceitar outro',
        dataADefinir: 'Data a definir',
      },
      motivo: {
        codigo_invalido: 'Código inválido',
        convite_expirado: 'Convite expirado',
        convite_ja_usado: 'Convite já foi usado',
        convite_revogado: 'Convite foi revogado pelo Mestre',
        pj_nao_pertence: 'Esse personagem não é seu',
        pj_nao_encontrado: 'Personagem não encontrado',
        pj_ja_vinculado: 'Esse personagem já está nessa mesa',
        nao_autenticado: 'Sessão expirada — faça login de novo',
      },
      aceitarModal: {
        concluir: 'Concluir',
        entrarMesa: 'Entrar em uma mesa',
        depois: 'Depois',
        convitePrompt: 'Recebeu um código de convite de um Mestre? Use-o para levar {nomePj} para uma história.',
      },
    },
    historias: {
      lista: {
        carregando: 'Abrindo os pergaminhos…',
        erroTabela: "Confira se a tabela 'historias' existe no Supabase.",
        comecarAventura: 'Comece uma nova aventura quando estiver pronto',
        limitePlanoFree: 'Você atingiu o limite de histórias do plano gratuito — faça um upgrade',
        novaHistoria: 'Nova história',
      },
      card: {
        batalhas: 'Batalhas',
        convites: 'Convites',
        lore: 'Lore',
        loreTip: 'Lore (NPCs, Reinos, Cidades)',
        lojaTip: 'Loja ({qtd})',
        loja: 'Loja',
        editar: 'Editar',
        excluir: 'Excluir',
        protagonistas: 'Protagonistas',
      },
      excluirModal: {
        titulo: 'Excluir?',
        confirmar: 'Excluir',
        aviso: 'A história "{titulo}" será removida permanentemente.',
      },
      loja: {
        shop: 'Loja',
        shopSub: 'Itens à venda para os jogadores de {titulo}.',
        catalog: 'Catálogo',
        catalogSub: 'Busque por nome, descrição ou origem.',
        empty: 'Escolha um item no catálogo',
        none: 'Nenhum item corresponde.',
        loading: 'Abrindo o catálogo…',
        price: 'Preço',
        stock: 'Estoque',
        remove: 'Remover',
        cancel: 'Cancelar',
        save: 'Salvar',
        saving: 'Salvando…',
        search: 'Buscar…',
        allGroups: 'Todos os grupos',
        clear: 'Limpar',
        inDesc: 'na descrição',
        inOrig: 'na origem',
        inDetails: 'nos detalhes',
        catalogPrice: 'Preço do catálogo',
        addToShop: 'Adicionar',
        origin: 'Origem',
        liquid: 'líquido',
        magic: 'mágico',
        moedaOuro: 'O',
        moedaPrata: 'P',
        moedaCobre: 'C',
        moedaLatao: 'L',
        gratis: 'grátis',
        inShopSingular: '{n} item na loja',
        inShopPlural: '{n} itens na loja',
        showing: '{n} de {total}',
        paginaPrimeira: 'Primeira página',
        paginaAnterior: 'Anterior',
        paginaProxima: 'Próxima',
        paginaUltima: 'Última página',
        paginaInfo: 'Página {atual} de {total}',
      },
      novaModal: {
        editarTitulo: 'Editar história',
        novaTitulo: 'Nova história',
        salvando: 'Salvando…',
        salvar: 'Salvar',
        criar: 'Criar',
        titulo: 'Título',
        tituloPlaceholder: 'A Sombra de Verrogar',
        reino: 'Reino',
        reinoPlaceholder: 'Verrogar',
        dataInicio: 'Data de início',
        dataInicioJogo: 'Data de início no jogo',
        criaturas: 'Criaturas',
        selecionadas: 'selecionadas',
        semCriaturas: 'Nenhuma criatura disponível no bestiário',
      },
    },
    lore: {
      form: {
        nome: 'Nome',
        descricao: 'Descrição',
        imagem: 'Imagem (URL, opcional)',
        deus: 'Deus',
        raca: 'Raça',
        localizacao: 'Localização',
        cidadeNatal: 'Cidade Natal',
        classeSocial: 'Classe Social',
        idade: 'Idade',
        familia: 'Família',
        relacao: 'Relação',
        status: 'Status',
        rumores: 'Rumores',
        icone: 'Ícone (URL, opcional)',
        governo: 'Governo',
        cultura: 'Cultura',
        historiaRecente: 'História recente',
        reino: 'Reino',
        populacao: 'População',
        capitalDoReino: 'É a capital do reino',
      },
    },
    inventario: {
      abaterEPreparar: 'Abater e preparar {nome}? Você receberá {qtd}× {consumivel}.',
      abrindoAsAlgibeiras: 'Abrindo as algibeiras…',
      aprendendo: 'Aprendendo…',
      aprender: 'Aprender',
      armaduras: 'Armaduras',
      armazenar: 'Armazenar',
      buscar: 'Buscar…',
      cancelar: 'Cancelar',
      capacidade: 'Capacidade',
      cargaPesada: 'Carga pesada',
      carregando: 'Carregando',
      confiraSeATabela: 'Confira se a tabela \'itens\' e a coluna \'inventario\' existem no Supabase.',
      confirmar: 'Confirmar',
      cuidadoEssaAcaoE: 'Cuidado, essa ação é irreversível.',
      deMax: 'de {max}',
      descartar: 'Descartar',
      desequipar: 'Desequipar',
      despir: 'Despir',
      destruirEsteItemPermanentemente: 'Destruir este item permanentemente?',
      destruirItem: 'Destruir item',
      detalhes: 'Detalhes',
      efeito: 'Efeito',
      enviando: 'Enviando…',
      equipar: 'Equipar',
      esteItemNaoE: 'Este item não é um pergaminho de magia.',
      falhaAoSalvar: 'Falha ao salvar',
      gratis: 'Grátis',
      liquidos: 'líquidos',
      magiaNaoEncontradaNo: 'Magia não encontrada no catálogo.',
      max: 'Máx',
      mesaUsouItem: '{nome} usou {item}.',
      moedas: 'Moedas',
      naoFoiPossivelAprender: 'Não foi possível aprender a magia.',
      nenhumRecipienteCompativelNo: 'Nenhum recipiente compatível no inventário',
      nivelDeMagiaInvalido: 'Nível de magia inválido no pergaminho.',
      oNivelDaMagia: 'O nível da magia passa do seu estágio.',
      ocupadoPorEquip: '{slot} ocupado por equipamento.',
      outros: 'Outros',
      pergaminhoNaoEncontradoNo: 'Pergaminho não encontrado no inventário.',
      personagemNaoEncontrado: 'Personagem não encontrado.',
      peso: 'Peso',
      pontosDeMagiaInsuficientes: 'Pontos de magia insuficientes.',
      precisaMaosLivres: 'Precisa de {maos} mão(s) livre(s) ({livres} livre{s}).',
      preparar: 'Preparar',
      prepararAnimal: 'Preparar animal',
      proibidoParaRaca: 'Proibido para {raca}.',
      pt: 'pt',
      ptBr: 'pt-BR',
      salvando: 'Salvando…',
      salvo: 'Salvo',
      semSlotDefinido: 'Sem slot definido.',
      semSlotDefinidoPara: 'Sem slot definido para este item.',
      simDestruir: 'Sim, destruir',
      simPreparar: 'Sim, preparar',
      simUsar: 'Sim, usar',
      slotCheio: 'Slot cheio ({usado}/{max}).',
      slotOcupado: 'Slot {slot} ocupado.',
      sobrecarregado: 'Sobrecarregado!',
      solidos: 'sólidos',
      suaProfissaoNaoPode: 'Sua profissão não pode aprender essa magia.',
      tituloArmazenar: 'Armazenar {nome}',
      tituloDestruir: 'Destruir {nome}',
      tituloRetirar: 'Retirar {nome}',
      tituloUsar: 'Usar {nome}',
      todos: 'Todos',
      transferir: 'Transferir',
      usar: 'Usar',
      usarEsteItem: 'Usar este item?',
      usarItem: 'Usar item',
      vestimentas: 'Vestimentas',
      vestir: 'Vestir',
      voceJaTemEssa: 'Você já tem essa magia neste nível ou superior.',
      voceNaoEstaAutenticado: 'Você não está autenticado.',
      voceNaoTemNenhum: 'Você não tem nenhum pertence.',
      vocePrecisaAprenderO: 'Você precisa aprender o nível anterior primeiro.',
      zerar: 'Zerar',
    },
    loja: {
      abraFicha: 'Abra a ficha de um personagem para acessar a loja dele',
      abrindoALoja: 'Abrindo a loja…',
      absorcao: 'Absorção',
      alcance: 'Alcance',
      armazena: 'Armazena',
      buscar: 'Buscar…',
      cancelar: 'Cancelar',
      comprar: 'Comprar',
      comprou: 'Você comprou {qtd} {nome}.',
      dano: 'Dano',
      de: 'de',
      e: ' e ',
      efeito: 'Efeito',
      escolhaUmRecipiente: 'Escolha um recipiente',
      esgotado: 'Esgotado',
      estoque: 'estoque',
      gratuito: 'Gratuito',
      guardarEm: 'Guardar em',
      livre: 'livre',
      moedasInsuficientes: 'Moedas insuficientes',
      nenhumaMoeda: 'nenhuma moeda',
      oMestreAindaNao: 'O mestre ainda não disponibilizou itens à venda',
      ocupa: 'Ocupa',
      outros: 'Outros',
      precisaEspacoTipo: 'Precisa de {n} de espaço {tipo}, livre {livre}',
      precisaLivre: 'precisa de {n} livre',
      precoUnitario: 'Preço unitário',
      ptBr: 'pt-BR',
      quantidade: 'Quantidade',
      recipientePrecisaLivre: 'Recipiente precisa de {n}, livre {livre}',
      semRecipienteCompativelCompre: 'Sem recipiente compatível — compre um antes',
      soRestam: 'Só {n} restante(s)',
      suasMoedasNaoFecham: 'Suas moedas não fecham o valor exato (sem troco)',
      tipoLiquido: 'líquido',
      tipoSolido: 'sólido',
      todos: 'Todos',
      totalQtd: 'Total ({n})',
      voceTem: 'Você tem',
      motivos: {
        sem_historia: 'Sem história para este personagem',
        item_nao_listado: 'Item não está mais à venda',
        item_nao_existe: 'Item não encontrado',
        estoque_insuficiente: 'Estoque esgotado',
        moedas_insuficientes: 'Moedas insuficientes',
        moedasInsuficientesCusto: 'Moedas insuficientes (custo: {custo} latão)',
        espaco_insuficiente: 'Espaço insuficiente',
        espacoInsuficienteDet: 'Espaço insuficiente (precisa {ocupa}, livre {livre})',
        recipiente_obrigatorio: 'Consumíveis e moedas precisam ir dentro de um recipiente',
        moedas_nao_fecham: 'Suas moedas não fecham o valor exato (sem troco)',
        recipiente_invalido: 'Recipiente inválido',
        tipo_incompativel: 'O recipiente não aceita esse tipo de item',
        pj_nao_encontrado: 'Personagem não encontrado',
        quantidade_invalida: 'Quantidade inválida',
      },
    },
    batalha: {
      verboAtacar: 'Atacar',
      verboResistir: 'Resistir',
      verboUsar: 'Usar',
      jaRolouContinueEm: 'Já rolou — continue em {v}.',
      statusAtivo: 'Ativo',
      statusPassou: 'Passou',
      statusDesmaiado: 'Desmaiado',
      statusMorto: 'Morto',
      statusDesistiu: 'Desistiu',
      seuStatusPassando: 'Seu status: {status} — passando a vez…',
      abrir: 'Abrir',
      absurdoRoleNovamentePara: '⚠ Absurdo — role novamente para o efeito crítico no alvo.',
      acao: 'Ação',
      alvo: 'Alvo',
      alvoNoD20: 'Alvo no d20',
      aplicadoJunto: '×{qtd}, aplicado junto',
      aplicar: 'Aplicar',
      arma: 'Arma',
      ateOFimDa: 'até o fim da batalha',
      ativa: 'Ativa',
      ausente: 'ausente',
      auto: 'auto',
      autoDano: ' · auto-dano',
      batalha: 'Batalha',
      batalhaEmAndamentoRodada: 'Batalha em andamento · rodada {rodada}',
      batalhaEmMontagem: 'Batalha em montagem',
      batalhas: 'Batalhas',
      cancelar: 'Cancelar',
      carregandoBatalha: 'Carregando batalha…',
      carregandoBatalhas: 'Carregando batalhas…',
      cliqueParaRemover: 'clique para remover',
      coluna: 'Coluna',
      colunaDeAcao: 'Coluna de Ação',
      colunaDeAcao7: 'Coluna de Ação (-7…50)',
      concluaARolagemPendente: 'Conclua a rolagem pendente primeiro',
      concluir: 'Concluir',
      confirmar: 'Confirmar',
      crU00edticoPulaEh: 'cr\\u00edtico (pula EH)',
      criando: 'Criando…',
      criarBatalha: 'Criar batalha',
      criaturas: 'Criaturas',
      critico: ' · crítico!',
      critico2: ' · crítico',
      criticoAlvo: 'Crítico — alvo',
      criticoEmSiMesmo: 'Crítico em si mesmo',
      criticoNoAlvo: 'Crítico no alvo',
      cura: 'Cura',
      dano: 'Dano',
      dano2: 'dano',
      dano3: 'dano',
      danoRodada: 'dano/rodada',
      defesaResist120: 'Defesa / Resist. (1-20)',
      desmarcarTodos: 'Desmarcar todos',
      df: 'DF',
      eASuaVez: 'É a sua vez',
      eAVezDe: 'É a vez de {nome}',
      empate: 'Empate',
      empateRoleDeNovo: 'Empate — role de novo',
      empateRoleDeNovo2: 'Empate — role de novo',
      empateRoleOD20: 'Empate — role o d20 de novo.',
      encerrada: 'Encerrada',
      encerrar: 'Encerrar',
      encerrar2: 'Encerrar',
      encerrarArquivaOLog: 'Encerrar arquiva o log e remove esta batalha. Escolha o que persistir nos PJs:',
      encerrarComSequelas: 'Encerrar com sequelas',
      envenenado: 'Envenenado',
      erra: 'erra',
      errou: 'Errou',
      essaEAHora: 'Essa é a hora de escolher quem participará da batalha. Selecione os personagens dos jogadores e as criaturas que farão parte do confronto. Após definir os combatentes, tudo estará pronto para iniciar o combate e acompanhar cada turno da batalha.',
      estagio: 'Estágio',
      esteLutadorNaoTem: 'Este lutador não tem habilidades.',
      esteLutadorNaoTem2: 'Este lutador não tem técnicas.',
      excluir: 'Excluir',
      expandirRecolherBarrasDe: 'Expandir/recolher barras de ',
      falhaAoSalvar: 'Falha ao salvar',
      falhaCriticaRoleNovamente: '⚠ Falha Crítica — role novamente para o efeito em si mesmo.',
      falhaCriticaSiMesmo: 'Falha Crítica — si mesmo',
      falhaMotivo: 'Falha: {motivo}',
      feridoS: 'ferido(s)',
      filtrar: 'Filtrar…',
      forcaDeAtaque: 'Força de Ataque',
      forcaDeAtaque1: 'Força de Ataque (1-20)',
      forcaDeDefesa: 'Força de Defesa',
      fracasso: 'Fracasso',
      habilidade: 'Habilidade',
      iniciando: 'Iniciando…',
      iniciar: 'Iniciar',
      inverterSelecao: 'Inverter seleção',
      item: 'Item',
      jogadores: 'Jogadores',
      karmaInsuficiente: 'Karma insuficiente',
      magia: 'Magia',
      maisUmaDeCada: 'Mais uma de cada',
      montagem: 'Montagem',
      mortoS: 'morto(s)',
      mudarEstado: 'Mudar estado',
      naoResistiu: 'Não resistiu',
      nenhumVinculadoAEsta: 'Nenhum vinculado a esta história',
      nenhuma: '— nenhuma —',
      nenhumaBatalhaNestaHistoria: 'Nenhuma batalha nesta história ainda.',
      novaBatalha: 'Nova batalha',
      novaRodada: 'Nova Rodada',
      pa: 'PA',
      participantes: 'participantes',
      passar: 'Passar',
      persistemComEf0: 'persistem com EF=0',
      pjsFeridosMantemAs: 'PJs feridos mantêm as pools atuais na história',
      pjsFeridosVoltamAo: 'PJs feridos voltam ao máximo na história',
      pool: 'Pool',
      ptBr: 'pt-BR',
      quantidade: 'Quantidade',
      resisteSeD20Alvo: 'resiste se d20 > alvo',
      resistencia: 'Resistência',
      resistenciaFisica: 'Resistência Física',
      resistenciaMagica: 'Resistência Mágica',
      resistiu: 'Resistiu',
      restaurarEEncerrar: 'Restaurar e encerrar',
      rodada: 'Rodada',
      rodadaSRestantes: 'rodada(s) restantes',
      rodadas: 'rodadas',
      rolagem: 'Rolagem: ',
      rolandoDadoPara: 'Rolando dado para ',
      rolarD20: 'Rolar d20',
      rolarD20DeCritico: 'Rolar d20 de crítico',
      rolarDeNovo: 'Rolar de novo',
      selecionarTodos: 'Selecionar todos',
      semAcoesDeCombate: 'Sem ações de combate disponíveis para este lutador.',
      semAlvosValidos: 'Sem alvos válidos.',
      semEfeitoMecanicoSo: 'Sem efeito mecânico — só consome o item.',
      semItensConsumiveisNo: 'Sem itens consumíveis no inventário.',
      semPaDisponivel: 'Sem PA disponível',
      semResultados: 'Sem resultados',
      seuStatus: 'Seu status: {status}',
      sucesso: 'Sucesso',
      tecnica: 'Técnica',
      tecnicaOpcional: 'Técnica (opcional)',
      todosOsPjsNo: 'Todos os PJs no máximo.',
      tudoProntoParaO: 'Tudo pronto para o início da batalha. A ordem de ação, ou iniciativa, é determinada pela velocidade de cada participante.',
      umaDeCada: 'Uma de cada',
      valor: 'valor',
      veneno: 'Veneno',
      voce: ' (você)',
      voltarAFicha: 'Voltar à ficha',
      voltarAsHistorias: 'Voltar às histórias',
      zerarTodas: 'Zerar todas',
    },
  },
  en: {
    nav: { features: 'Features', pricing: 'Pricing', faq: 'Questions', signin: 'Sign in' },
    cta_main: 'Forge my table',
    cta_ghost: 'See the plans',
    hero: {
      eyebrow: 'A platform for Game Masters & Players',
      h1_pre: 'Your RPG tabletop',
      h1_accent: 'will never be the same',
      sub: 'Build campaigns, sheets, characters and lore in one place — for any RPG system. Play remote without losing the soul of the table.',
      micro: ['Instant access', 'No card', 'Free forever plan'],
    },
    opening: {
      eyebrow: 'Chapter I — The Promise',
      h: 'Every session begins with a promise: tonight will be epic.',
      p1: 'Then game time arrives. Someone forgot their sheet. Another lost the rulebook. The GM spent the whole week prepping — and yet, something is missing.',
      p2: 'Menestrel was born for this. One platform where GM and players meet, with everything the table needs under one roof: sheets, characters, creatures, world, turn-based combat, inventory and shop.',
      p3: 'You pick the system. Menestrel handles the rest.',
    },
    pain: {
      eyebrow: 'Chapter II — The Shadows',
      h: 'You love RPG. But the game became work.',
      list: [
        'Spent hours writing an characters the party killed in two turns?',
        'Opened 5 tabs just to run a single session — sheet here, map there, rule somewhere else?',
        'Lost a campaign because the group could not meet in person and nobody wanted to migrate to a complicated tool?',
        'Gave up GMing a new system because the rules were a labyrinth?',
        'Watched a player drop the table because "it is hard to keep up"?',
        'Felt that instead of telling a story, you became a spreadsheet admin?',
      ],
      quote: 'The table should be where imagination runs free. Not where it drowns in logistics.',
    },
    solution: {
      eyebrow: 'Chapter III — The Solution',
      h: 'Menestrel is the invisible bard at your table.',
      p1: 'While you focus on telling the story, it handles what steals your time: sheets, characters, creatures, turn order, inventory, and the lore of your world.',
      p2: 'And the most important: it works with any system. You customize, Menestrel adapts.',
      card_h: 'Supported systems',
      card_p: 'D&D, Pathfinder, Call of Cthulhu, Vampire, GURPS, or your homebrew system. All online, all in sync — remote tables without losing the blood, sweat and smoke of the tavern.',
      systems: ['D&D 5e', 'Tormenta20', 'Pathfinder', 'Call of Cthulhu', 'Vampire: The Masquerade', 'GURPS'],
      custom: 'Homebrew',
      tree: [
        { label: 'Organizes', items: ['sheets', 'campaigns', 'world & lore'] },
        { label: 'Manages', items: ['characters', 'creatures', 'bestiary'] },
        { label: 'Controls', items: ['combat turns', 'energies & conditions', 'damage & spells'] },
        { label: 'Tracks', items: ['inventory', 'shop', 'coin chest'] },
      ],
    },
    benefits: {
      eyebrow: 'Chapter IV — The Gifts',
      h: 'What changes when Menestrel joins the table.',
      sub: 'At least eight concrete gains for GMs and players. Not vague promises — battle-tested by people who have loved and played RPG for years.',
      stages: [
        { badge: 'Prep', h: 'Prep the session in minutes, not hours.', checks: ['Characters and creatures in minutes', 'Sheets that never disappear'] },
        { badge: 'The Table', h: 'The whole table in one tab.', checks: ['Sheets, maps, shop and inventory', 'Goodbye to the 12-tab chaos'] },
        { badge: 'Combat', h: 'Turn-based combat without the headache.', checks: ['Turns, energies and conditions', 'Damage and spells computed for you'] },
        { badge: 'Anywhere', h: 'The table goes on, wherever life takes you.', checks: ['Web on any device', 'Any system, your way'], featured: true, cta: 'Forge my table' },
      ],
      list: [
        { icon: 'Scroll', t: 'Tell stories, not spreadsheets.', d: 'You go back to being the GM, not the administrator. Logistics disappear — only the narrative stays.' },
        { icon: 'Tower', t: 'The whole table in one tab.', d: 'Sheets, characters, creatures, map, combat, shop, inventory. The 12-tab chaos ends.' },
        { icon: 'Compass', t: 'Any system, your way.', d: 'Full customization to run D&D, Pathfinder, Vampire or your own homebrew without ties.' },
        { icon: 'Sword', t: 'Turn-based combat without the headache.', d: 'Initiative, HP, conditions, damage — the system tracks, you narrate.' },
        { icon: 'Compass', t: 'Play from anywhere.', d: 'The group moved, your friend works abroad, a baby arrived. The table goes on. Web, any device.' },
        { icon: 'Skull', t: 'Characters and creatures in minutes.', d: 'Build a memorable villain before next session — not after an all-nighter of prep.' },
        { icon: 'Scroll', t: 'Sheets that never disappear.', d: 'That character from 3 years ago? Still there. Saved. Whole. Waiting.' },
        { icon: 'Flame', t: 'Simple on top, deep underneath.', d: 'A newcomer runs the first session in minutes. A veteran finds enough customization for any homebrew.' },
      ],
    },
    social: {
      eyebrow: 'Chapter V — The Guild',
      h: 'The tavern is already full.',
      stats: [
        { n: '2,847', l: 'Tables forged', note: '(sample)' },
        { n: '11,420', l: 'GMs & players', note: '(sample)' },
        { n: '4.8', l: 'Beta rating', note: 'out of 5 (sample)' },
      ],
      testimonials: [
        { q: 'I used to prep for 6 hours. Now it takes 40 minutes. I got my life back — and the table got better.', who: 'Rafael "Corvus"', role: 'GM, D&D 5e for 8 years' },
        { q: 'I am a player, not a tech person. In 5 minutes I had my sheet. No manual, nobody teaching me. It just worked.', who: 'Marina Aguiar', role: 'Player for 3 years' },
        { q: 'We migrated our campaign from another platform in one afternoon. The group did not even complain — which never happens.', who: 'Diego "Khorn"', role: 'GM, Five Blades crew' },
      ],
    },
    plans: {
      eyebrow: 'Chapter VI — The Offer',
      h: 'Two plans. You choose the size of the adventure.',
      free: {
        tag: 'Menestrel plan',
        name: 'Free',
        price: '$ 0',
        unit: '/forever',
        group: '',
        features: [
          'Up to 5 character sheets',
          'Up to 3 campaigns',
          'Turn-based combat system',
          'Basic characters and creatures',
          'Inventory and shop',
          'Web on any device',
        ],
        cta: 'Start free',
      },
      pro: {
        tag: 'Menestrel plan',
        name: 'Legendary',
        price: '$ 9.90',
        unit: '/month',
        group: '',
        features: [
          'Everything in Free, no limits',
          'Unlimited sheets, campaigns, characters',
          'Advanced world building',
          'Priority GM support',
          'All future features, no extra cost',
          'Cancel anytime, no fees',
        ],
        cta: 'I want Legendary',
      },
    },
    guarantee: {
      eyebrow: 'Bard\u2019s Guarantee',
      h: '7 days. Zero risk.',
      p: 'Subscribe to Legendary, test it freely for 7 days. If Menestrel does not save your time, does not make your table flow, simply is not for you — we refund 100%.',
    },
    scarcity: {
      eyebrow: 'Founders Batch',
      h: 'The first 500 become Founding Members.',
      p: 'Lock $ 9.90/month forever (even when the price goes up), early access to new features, and the exclusive Founder badge.',
      filled: 365,
      total: 500,
      warn: '⚠ Technical briefing: this scarcity must be real. If not, remove this block before publishing — fake urgency burns the brand.',
    },
    objections: {
      eyebrow: 'Chapter VII — The Doubts',
      h: 'I thought of that, but...',
      list: [
        { q: 'I already use Roll20 / Foundry / another tool.', a: 'We get it — and respect it. But Menestrel is not another complex tool that needs a 3-hour tutorial. It is built to run the first session in minutes, without becoming a software technician. Test it free and compare.' },
        { q: 'Pen and paper always worked for me.', a: 'And it still does. Menestrel does not replace the magic of the physical table — it rescues that magic when the group cannot be together. For the day someone moved, had a child, switched shifts. The campaign does not die.' },
        { q: 'My group will not migrate.', a: 'It is free. No install. No card. They join through the browser. If someone complains after a session, you go back. But it is rare — because Menestrel disappears during the game.' },
        { q: 'It will get expensive long-term.', a: 'Free is free forever. If you subscribe to Legendary as a group, it is less than $ 6 per person per month — less than a coffee. For a friction-free table, every month.' },
      ],
    },
    faq: {
      eyebrow: 'Scroll of Questions',
      h: 'Frequently Asked Questions.',
      list: [
        { q: 'What RPG systems does Menestrel support?', a: 'Any of them. D&D 5e, Pathfinder, Call of Cthulhu, Vampire: The Masquerade, GURPS, your own systems — you customize sheets, rules and attributes the way your table plays.' },
        { q: 'I am a beginner. Can I use it?', a: 'Yes. Menestrel was built for people who never opened a digital RPG platform before. Create your first sheet in minutes. No 200-page manual.' },
        { q: 'I am a veteran GM with homebrew tables. Can I customize?', a: 'Yes. Customization is total — you define attributes, skills, rules, classes. Menestrel molds to your system, not the other way around.' },
        { q: 'Does it work on mobile?', a: 'Yes. It is web — runs on any browser, phone, tablet or computer.' },
        { q: 'What if I do not like Legendary?', a: 'You have a 7-day guarantee. Ask for a refund, we return 100%. No questions, no paperwork.' },
        { q: 'How does the group plan work ($ 29.90)?', a: 'You subscribe and unlock access for up to 5 people (GM + 4 players, or 5 GMs, as you prefer). Less than $ 6 per head.' },
        { q: 'Can I cancel anytime?', a: 'Yes. No fee. No call to retain you. Two clicks in the panel.' },
        { q: 'Are my sheets saved if I cancel?', a: 'Yes. Everything stays in your account. If you come back one day, your table is waiting.' },
      ],
    },
    final: {
      eyebrow: 'Last chapter',
      h_a: 'The next campaign has already started',
      h_b: 'inside your head.',
      p: 'The characters exist. The villains wait. The world only needs someone to tell it. Stop postponing. Stop improvising across 8 tabs. The tavern is open. The bard has tuned the lute.',
      cta: 'Start my table for free',
      micro: 'Instant access • No card • Free forever',
      ps: 'Every great campaign starts with a small choice. Today yours is: keep losing hours prepping tables that exhaust you, or start free and see, in a single session, what changes when Menestrel handles logistics and you go back to telling the story.',
      pps: 'Legendary has a full 7-day guarantee. You test risk-free. And if you join during launch, you lock $ 9.90/month forever as a Founder. When the seats fill, the price goes up.',
    },
    modal: {
      title: 'Forge the table',
      sub: 'Instant access. No card. Free forever.',
      name: 'GM name',
      email: 'Contact scroll (email)',
      pass: 'Secret password',
      consent: 'I agree to the Privacy Policy and to the processing of my data under data protection laws.',
      submit: 'Seal the pact',
      success_h: 'The tavern is open for you.',
      success_p: 'We sent your access to the scroll. Check your inbox — and may your campaign be epic.',
      close: 'Close',
      err_name: 'Tell the Menestrel your name.',
      err_email: 'Invalid email.',
      err_pass: 'Password needs 6+ characters.',
      err_consent: 'Accept the policy to seal the pact.',
    },
    footer: {
      tag: 'The invisible bard of your table.',
      links: ['Terms', 'Privacy', 'Contact', 'Status'],
      copy: '© 2026 Menestrel RPG. Forged with love for the table.',
    },
    convites: {
      mng: {
        titulo: 'Manage invites',
        fechar: 'Close',
        gerando: 'Generating…',
        novoConvite: 'New invite',
        descricao: 'Generate codes to invite players to the adventure "{tituloHistoria}".',
        carregando: 'Loading…',
        vazio: "You haven't generated any invitations yet.",
        uiKitAusente: 'UI kit not loaded (ui-bridge).',
        copiar: 'Copy',
        copiado: 'Copied',
        reativar: 'Reactivate',
        remover: 'Remove',
        falhouComMotivo: 'Failed: {motivo}',
        falhouDesconhecido: 'unknown',
      },
      status: {
        ativo: 'Active',
        usado: 'Used',
        revogado: 'Revoked',
        expirado: 'Expired',
      },
      jogador: {
        digiteCodigoPrimeiro: 'Enter a code first',
        semPersonagem: "You haven't created a character yet — you need to create one before accepting the invitation",
        instrucao: 'To join an adventure, paste the code the Game Master shared with you into the field below.',
        continuar: 'Continue',
        escolherPj: 'Code: {codigo}. Choose which character to link to this story:',
        voltar: 'Back',
        aceitando: 'Accepting…',
        aceitarConvite: 'Accept invite',
        conviteAceito: 'Invite accepted!',
        sucesso: 'Your character {pjNome} is now part of {historiaTitulo}.',
        aceitarOutro: 'Accept another',
        dataADefinir: 'Date to be set',
      },
      motivo: {
        codigo_invalido: 'Invalid code',
        convite_expirado: 'Invite expired',
        convite_ja_usado: 'Invite already used',
        convite_revogado: 'Invite was revoked by the Master',
        pj_nao_pertence: 'That character is not yours',
        pj_nao_encontrado: 'Character not found',
        pj_ja_vinculado: 'That character is already in this table',
        nao_autenticado: 'Session expired — sign in again',
      },
      aceitarModal: {
        concluir: 'Done',
        entrarMesa: 'Join a table',
        depois: 'Later',
        convitePrompt: 'Got an invite code from a Game Master? Use it to bring {nomePj} into a story.',
      },
    },
    historias: {
      lista: {
        carregando: 'Loading stories…',
        erroTabela: "Make sure the 'historias' table exists in Supabase.",
        comecarAventura: 'Start a new adventure when you are ready',
        limitePlanoFree: "You've reached the story limit for the free plan — upgrade now.",
        novaHistoria: 'New story',
      },
      card: {
        batalhas: 'Battles',
        convites: 'Invites',
        lore: 'Lore',
        loreTip: 'Lore (NPCs, Kingdoms, Cities)',
        lojaTip: 'Shop ({qtd})',
        loja: 'Shop',
        editar: 'Edit',
        excluir: 'Delete',
        protagonistas: 'Protagonists',
      },
      excluirModal: {
        titulo: 'Delete?',
        confirmar: 'Delete',
        aviso: 'The story "{titulo}" will be permanently removed.',
      },
      loja: {
        shop: 'Shop',
        shopSub: 'Items for sale to players of {titulo}.',
        catalog: 'Catalog',
        catalogSub: 'Search…',
        empty: 'Pick from the catalog',
        none: 'No items match.',
        loading: 'Loading catalog…',
        price: 'Price',
        stock: 'Stock',
        remove: 'Remove',
        cancel: 'Cancel',
        save: 'Save',
        saving: 'Saving…',
        search: 'Search…',
        allGroups: 'All groups',
        clear: 'Clear',
        inDesc: 'in description',
        inOrig: 'in origin',
        inDetails: 'in details',
        catalogPrice: 'Catalog price',
        addToShop: 'Add',
        origin: 'Origin',
        liquid: 'liquid',
        magic: 'magic',
        moedaOuro: 'g',
        moedaPrata: 's',
        moedaCobre: 'c',
        moedaLatao: 'b',
        gratis: 'free',
        inShopSingular: '{n} item in shop',
        inShopPlural: '{n} items in shop',
        showing: '{n} of {total}',
        paginaPrimeira: 'First page',
        paginaAnterior: 'Previous',
        paginaProxima: 'Next',
        paginaUltima: 'Last page',
        paginaInfo: 'Page {atual} of {total}',
      },
      novaModal: {
        editarTitulo: 'Edit story',
        novaTitulo: 'New story',
        salvando: 'Saving…',
        salvar: 'Save',
        criar: 'Create',
        titulo: 'Title',
        tituloPlaceholder: 'The Shadow of Verrogar',
        reino: 'Realm',
        reinoPlaceholder: 'Kingdom of Verrogar',
        dataInicio: 'Start date',
        dataInicioJogo: 'Start in-game date',
        criaturas: 'Creatures',
        selecionadas: 'selected',
        semCriaturas: 'No creatures in the bestiary yet',
      },
    },
    lore: {
      form: {
        nome: 'Name',
        descricao: 'Description',
        imagem: 'Image (URL, optional)',
        deus: 'Deity',
        raca: 'Race',
        localizacao: 'Location',
        cidadeNatal: 'Hometown',
        classeSocial: 'Social Class',
        idade: 'Age',
        familia: 'Family',
        relacao: 'Relationship',
        status: 'Status',
        rumores: 'Rumors',
        icone: 'Icon (URL, optional)',
        governo: 'Government',
        cultura: 'Culture',
        historiaRecente: 'Recent History',
        reino: 'Realm',
        populacao: 'Population',
        capitalDoReino: "Is the realm's capital",
      },
    },
    inventario: {
      abaterEPreparar: 'Slaughter and process {nome}? You will receive {qtd}× {consumivel}.',
      abrindoAsAlgibeiras: 'Loading inventory…',
      aprendendo: 'Learning…',
      aprender: 'Learn',
      armaduras: 'Armor',
      armazenar: 'Store',
      buscar: 'Search',
      cancelar: 'Cancel',
      capacidade: 'Capacity',
      cargaPesada: 'Heavy load',
      carregando: 'Carried',
      confiraSeATabela: 'Make sure tables \'itens\' and column \'inventario\' exist in Supabase.',
      confirmar: 'Confirm',
      cuidadoEssaAcaoE: 'Caution, this action is irreversible.',
      deMax: 'of {max}',
      descartar: 'Descart',
      desequipar: 'Unequip',
      despir: 'Take off',
      destruirEsteItemPermanentemente: 'Destroy this item permanently?',
      destruirItem: 'Destroy item',
      detalhes: 'Details',
      efeito: 'Effect',
      enviando: 'Sending…',
      equipar: 'Equip',
      esteItemNaoE: 'This item is not a spell scroll.',
      falhaAoSalvar: 'Save failed',
      gratis: 'Free',
      liquidos: 'liquids',
      magiaNaoEncontradaNo: 'Spell not found in the catalog.',
      max: 'Max',
      mesaUsouItem: '{nome} used {item}',
      moedas: 'Coins',
      naoFoiPossivelAprender: 'Could not learn the spell.',
      nenhumRecipienteCompativelNo: 'No compatible container in inventory',
      nivelDeMagiaInvalido: 'Invalid spell level on the scroll.',
      oNivelDaMagia: 'Spell level exceeds your character\'s stage.',
      ocupadoPorEquip: '{slot} occupied by gear.',
      outros: 'Other',
      pergaminhoNaoEncontradoNo: 'Scroll not found in your inventory.',
      personagemNaoEncontrado: 'Character not found.',
      peso: 'Weight',
      pontosDeMagiaInsuficientes: 'Not enough magic points.',
      precisaMaosLivres: 'Needs {maos} free hand(s) ({livres} free).',
      preparar: 'Prepare',
      prepararAnimal: 'Prepare animal',
      proibidoParaRaca: 'Forbidden for {raca}.',
      pt: 'en',
      ptBr: 'en-US',
      salvando: 'Saving…',
      salvo: 'Saved ✓',
      semSlotDefinido: 'No slot defined.',
      semSlotDefinidoPara: 'No slot defined for this item.',
      simDestruir: 'Yes, destroy',
      simPreparar: 'Yes, prepare',
      simUsar: 'Yes, use',
      slotCheio: 'Slot full ({usado}/{max}).',
      slotOcupado: 'Slot {slot} occupied.',
      sobrecarregado: 'Overloaded!',
      solidos: 'solids',
      suaProfissaoNaoPode: 'Your class cannot learn this spell.',
      tituloArmazenar: 'Store {nome}',
      tituloDestruir: 'Destroy {nome}',
      tituloRetirar: 'Take out {nome}',
      tituloUsar: 'Use {nome}',
      todos: 'All',
      transferir: 'Transfer',
      usar: 'Use',
      usarEsteItem: 'Use this item?',
      usarItem: 'Use item',
      vestimentas: 'Worn',
      vestir: 'Wear',
      voceJaTemEssa: 'You already know this spell at this level or higher.',
      voceNaoEstaAutenticado: 'You are not signed in.',
      voceNaoTemNenhum: 'You have no possessions.',
      vocePrecisaAprenderO: 'You must learn the previous level first.',
      zerar: 'Reset',
    },
    loja: {
      abraFicha: 'Open a character\'s sheet to enter its shop',
      abrindoALoja: 'Opening the shop…',
      absorcao: 'Absorb',
      alcance: 'Range',
      armazena: 'Stores',
      buscar: 'Search',
      cancelar: 'Cancel',
      comprar: 'Buy',
      comprou: 'Bought {qtd} {nome}.',
      dano: 'Damage',
      de: 'of',
      e: ' and ',
      efeito: 'Effect',
      escolhaUmRecipiente: 'Choose a container',
      esgotado: 'Out of stock',
      estoque: 'stock',
      gratuito: 'Free',
      guardarEm: 'Store in',
      livre: 'free',
      moedasInsuficientes: 'Not enough coin',
      nenhumaMoeda: 'no coins',
      oMestreAindaNao: 'The Game Master has not listed any items yet',
      ocupa: 'Takes',
      outros: 'Other',
      precisaEspacoTipo: 'Needs {n} {tipo} space, free {livre}',
      precisaLivre: 'needs {n} free',
      precoUnitario: 'Unit price',
      ptBr: 'en-US',
      quantidade: 'Quantity',
      recipientePrecisaLivre: 'Container needs {n}, free {livre}',
      semRecipienteCompativelCompre: 'No compatible container — buy one first',
      soRestam: 'Only {n} left',
      suasMoedasNaoFecham: 'Your coins can’t make the exact price (no change)',
      tipoLiquido: 'liquid',
      tipoSolido: 'solid',
      todos: 'All',
      totalQtd: 'Total ({n})',
      voceTem: 'You have',
      motivos: {
        sem_historia: 'No story for this character',
        item_nao_listado: 'Item not listed in this shop',
        item_nao_existe: 'Item not found',
        estoque_insuficiente: 'Out of stock',
        moedas_insuficientes: 'Not enough coin',
        moedasInsuficientesCusto: 'Not enough coin (cost: {custo} brass)',
        espaco_insuficiente: 'Not enough space',
        espacoInsuficienteDet: 'Not enough space (needs {ocupa}, free {livre})',
        recipiente_obrigatorio: 'Consumables and coins must go inside a container',
        moedas_nao_fecham: 'Your coins can’t make the exact price (no change given)',
        recipiente_invalido: 'Invalid container',
        tipo_incompativel: 'Container does not accept this item type',
        pj_nao_encontrado: 'Character not found',
        quantidade_invalida: 'Invalid quantity',
      },
    },
    batalha: {
      verboAtacar: 'Attack',
      verboResistir: 'Resist',
      verboUsar: 'Use',
      jaRolouContinueEm: 'Already rolled — continue to confirm.',
      statusAtivo: 'Active',
      statusPassou: 'Passed',
      statusDesmaiado: 'Downed',
      statusMorto: 'Dead',
      statusDesistiu: 'Withdrew',
      seuStatusPassando: 'Your status: {status} — passing turn…',
      abrir: 'Open',
      absurdoRoleNovamentePara: '⚠ Absurd — roll again for critical effect on target.',
      acao: 'Action',
      alvo: 'Target',
      alvoNoD20: 'Target on d20',
      aplicadoJunto: '×{qtd}, applied together',
      aplicar: 'Apply',
      arma: 'Weapon',
      ateOFimDa: 'until battle ends',
      ativa: 'Active',
      ausente: 'missing',
      auto: 'auto',
      autoDano: ' · self-damage',
      batalha: 'Battle',
      batalhaEmAndamentoRodada: 'Battle in progress · round {rodada}',
      batalhaEmMontagem: 'Battle in setup',
      batalhas: 'Battles',
      cancelar: 'Cancel',
      carregandoBatalha: 'Loading battle…',
      carregandoBatalhas: 'Loading battles…',
      cliqueParaRemover: 'click to remove',
      coluna: 'Col',
      colunaDeAcao: 'Action column',
      colunaDeAcao7: 'Action column (-7…50)',
      concluaARolagemPendente: 'Finish the pending roll first',
      concluir: 'Done',
      confirmar: 'Confirm',
      crU00edticoPulaEh: 'critical (skips EH)',
      criando: 'Creating…',
      criarBatalha: 'Create battle',
      criaturas: 'Creatures',
      critico: ' · critical!',
      critico2: ' · critical',
      criticoAlvo: 'Critical — target',
      criticoEmSiMesmo: 'Critical on self',
      criticoNoAlvo: 'Critical on target',
      cura: 'Heal',
      dano: 'Damage',
      dano2: 'damage',
      dano3: 'dmg',
      danoRodada: 'dmg/round',
      defesaResist120: 'Defense / Resist. (1-20)',
      desmarcarTodos: 'Deselect all',
      df: 'DF',
      eASuaVez: 'It\'s your turn',
      eAVezDe: 'It\'s {nome}\'s turn',
      empate: 'Tie',
      empateRoleDeNovo: 'Tie — roll again',
      empateRoleDeNovo2: 'Tie — re-roll',
      empateRoleOD20: 'Tie — roll the d20 again.',
      encerrada: 'Ended',
      encerrar: 'End',
      encerrar2: 'Withdraw',
      encerrarArquivaOLog: 'Ending archives the log and removes this battle. Choose how to persist pools:',
      encerrarComSequelas: 'End with consequences',
      envenenado: 'Poisoned',
      erra: 'miss',
      errou: 'Miss',
      essaEAHora: 'Choose who will take part in the battle. Select the player characters and creatures that will join the confrontation. Once the combatants are set, everything will be ready to start combat and track each turn.',
      estagio: 'Stage',
      esteLutadorNaoTem: 'This fighter has no skills.',
      esteLutadorNaoTem2: 'This fighter has no techniques.',
      excluir: 'Delete',
      expandirRecolherBarrasDe: 'Toggle pools for ',
      falhaAoSalvar: 'Failed to save',
      falhaCriticaRoleNovamente: '⚠ Critical Failure — roll again for self-damage effect.',
      falhaCriticaSiMesmo: 'Critical Failure — self',
      falhaMotivo: 'Failed: {motivo}',
      feridoS: 'wounded',
      filtrar: 'Filter…',
      forcaDeAtaque: 'Attack force',
      forcaDeAtaque1: 'Attack force (1-20)',
      forcaDeDefesa: 'Defense force',
      fracasso: 'Failure',
      habilidade: 'Skill',
      iniciando: 'Starting…',
      iniciar: 'Start',
      inverterSelecao: 'Invert selection',
      item: 'Item',
      jogadores: 'Players',
      karmaInsuficiente: 'Not enough karma',
      magia: 'Spell',
      maisUmaDeCada: 'Add one more of each',
      montagem: 'Setup',
      mortoS: 'dead',
      mudarEstado: 'Change state',
      naoResistiu: 'Not resisted',
      nenhumVinculadoAEsta: 'None linked to this story',
      nenhuma: '— none —',
      nenhumaBatalhaNestaHistoria: 'No battles yet for this story.',
      novaBatalha: 'New battle',
      novaRodada: 'New Turn',
      pa: 'AP',
      participantes: 'participants',
      passar: 'Pass',
      persistemComEf0: 'persist with EF=0',
      pjsFeridosMantemAs: 'Wounded PCs keep current pools in the story',
      pjsFeridosVoltamAo: 'Wounded PCs return to max in the story',
      pool: 'Pool',
      ptBr: 'en-US',
      quantidade: 'Quantity',
      resisteSeD20Alvo: 'resists if d20 > target',
      resistencia: 'Resistance',
      resistenciaFisica: 'Physical Resistance',
      resistenciaMagica: 'Magic Resistance',
      resistiu: 'Resisted',
      restaurarEEncerrar: 'Restore & end',
      rodada: 'Round',
      rodadaSRestantes: 'rounds left',
      rodadas: 'rounds',
      rolagem: 'Roll: ',
      rolandoDadoPara: 'Rolling die for ',
      rolarD20: 'Roll d20',
      rolarD20DeCritico: 'Roll critical d20',
      rolarDeNovo: 'Roll again',
      selecionarTodos: 'Select all',
      semAcoesDeCombate: 'No combat actions available for this actor.',
      semAlvosValidos: 'No valid targets.',
      semEfeitoMecanicoSo: 'No mechanical effect — consumes the item only.',
      semItensConsumiveisNo: 'No consumable items in inventory.',
      semPaDisponivel: 'No AP left',
      semResultados: 'No results',
      seuStatus: 'Your status: {status}',
      sucesso: 'Success',
      tecnica: 'Technique',
      tecnicaOpcional: 'Technique (optional)',
      todosOsPjsNo: 'All PCs at full pools.',
      tudoProntoParaO: 'Everything is ready for the battle to begin. The turn order, or initiative, is determined by each participants speed.',
      umaDeCada: 'One of each',
      valor: 'amount',
      veneno: 'Poison',
      voce: ' (you)',
      voltarAFicha: 'Back to sheet',
      voltarAsHistorias: 'Back to stories',
      zerarTodas: 'Remove all',
    },
  },
};

window.COPY = COPY;

Object.assign(window, { COPY });